// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module forward_forward_Pipeline_VITIS_LOOP_41_2_p_ZL28RNN_INPUT_WEIGHTS_TRANSPOSED_2_ROM_AUTdEe (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 32;
parameter AddressWidth = 7;
parameter AddressRange = 100;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./forward_forward_Pipeline_VITIS_LOOP_41_2_p_ZL28RNN_INPUT_WEIGHTS_TRANSPOSED_2_ROM_AUTdEe.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

