// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module forward_forward_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_24_address0,
        input_24_ce0,
        input_24_we0,
        input_24_d0,
        input_23_address0,
        input_23_ce0,
        input_23_we0,
        input_23_d0,
        input_22_address0,
        input_22_ce0,
        input_22_we0,
        input_22_d0,
        input_21_address0,
        input_21_ce0,
        input_21_we0,
        input_21_d0,
        input_20_address0,
        input_20_ce0,
        input_20_we0,
        input_20_d0,
        input_19_address0,
        input_19_ce0,
        input_19_we0,
        input_19_d0,
        input_18_address0,
        input_18_ce0,
        input_18_we0,
        input_18_d0,
        input_17_address0,
        input_17_ce0,
        input_17_we0,
        input_17_d0,
        input_16_address0,
        input_16_ce0,
        input_16_we0,
        input_16_d0,
        input_15_address0,
        input_15_ce0,
        input_15_we0,
        input_15_d0,
        input_14_address0,
        input_14_ce0,
        input_14_we0,
        input_14_d0,
        input_13_address0,
        input_13_ce0,
        input_13_we0,
        input_13_d0,
        input_12_address0,
        input_12_ce0,
        input_12_we0,
        input_12_d0,
        input_11_address0,
        input_11_ce0,
        input_11_we0,
        input_11_d0,
        input_10_address0,
        input_10_ce0,
        input_10_we0,
        input_10_d0,
        input_9_address0,
        input_9_ce0,
        input_9_we0,
        input_9_d0,
        input_8_address0,
        input_8_ce0,
        input_8_we0,
        input_8_d0,
        input_7_address0,
        input_7_ce0,
        input_7_we0,
        input_7_d0,
        input_6_address0,
        input_6_ce0,
        input_6_we0,
        input_6_d0,
        input_5_address0,
        input_5_ce0,
        input_5_we0,
        input_5_d0,
        input_4_address0,
        input_4_ce0,
        input_4_we0,
        input_4_d0,
        input_3_address0,
        input_3_ce0,
        input_3_we0,
        input_3_d0,
        input_2_address0,
        input_2_ce0,
        input_2_we0,
        input_2_d0,
        input_1_address0,
        input_1_ce0,
        input_1_we0,
        input_1_d0,
        input_r_address0,
        input_r_ce0,
        input_r_we0,
        input_r_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_24_address0;
output   input_24_ce0;
output   input_24_we0;
output  [31:0] input_24_d0;
output  [5:0] input_23_address0;
output   input_23_ce0;
output   input_23_we0;
output  [31:0] input_23_d0;
output  [5:0] input_22_address0;
output   input_22_ce0;
output   input_22_we0;
output  [31:0] input_22_d0;
output  [5:0] input_21_address0;
output   input_21_ce0;
output   input_21_we0;
output  [31:0] input_21_d0;
output  [5:0] input_20_address0;
output   input_20_ce0;
output   input_20_we0;
output  [31:0] input_20_d0;
output  [5:0] input_19_address0;
output   input_19_ce0;
output   input_19_we0;
output  [31:0] input_19_d0;
output  [5:0] input_18_address0;
output   input_18_ce0;
output   input_18_we0;
output  [31:0] input_18_d0;
output  [5:0] input_17_address0;
output   input_17_ce0;
output   input_17_we0;
output  [31:0] input_17_d0;
output  [5:0] input_16_address0;
output   input_16_ce0;
output   input_16_we0;
output  [31:0] input_16_d0;
output  [5:0] input_15_address0;
output   input_15_ce0;
output   input_15_we0;
output  [31:0] input_15_d0;
output  [5:0] input_14_address0;
output   input_14_ce0;
output   input_14_we0;
output  [31:0] input_14_d0;
output  [5:0] input_13_address0;
output   input_13_ce0;
output   input_13_we0;
output  [31:0] input_13_d0;
output  [5:0] input_12_address0;
output   input_12_ce0;
output   input_12_we0;
output  [31:0] input_12_d0;
output  [5:0] input_11_address0;
output   input_11_ce0;
output   input_11_we0;
output  [31:0] input_11_d0;
output  [5:0] input_10_address0;
output   input_10_ce0;
output   input_10_we0;
output  [31:0] input_10_d0;
output  [5:0] input_9_address0;
output   input_9_ce0;
output   input_9_we0;
output  [31:0] input_9_d0;
output  [5:0] input_8_address0;
output   input_8_ce0;
output   input_8_we0;
output  [31:0] input_8_d0;
output  [5:0] input_7_address0;
output   input_7_ce0;
output   input_7_we0;
output  [31:0] input_7_d0;
output  [5:0] input_6_address0;
output   input_6_ce0;
output   input_6_we0;
output  [31:0] input_6_d0;
output  [5:0] input_5_address0;
output   input_5_ce0;
output   input_5_we0;
output  [31:0] input_5_d0;
output  [5:0] input_4_address0;
output   input_4_ce0;
output   input_4_we0;
output  [31:0] input_4_d0;
output  [5:0] input_3_address0;
output   input_3_ce0;
output   input_3_we0;
output  [31:0] input_3_d0;
output  [5:0] input_2_address0;
output   input_2_ce0;
output   input_2_we0;
output  [31:0] input_2_d0;
output  [5:0] input_1_address0;
output   input_1_ce0;
output   input_1_we0;
output  [31:0] input_1_d0;
output  [5:0] input_r_address0;
output   input_r_ce0;
output   input_r_we0;
output  [31:0] input_r_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] exitcond6079_fu_517_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] p_cast8_fu_548_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] phi_urem_fu_134;
wire   [10:0] idx_urem_fu_645_p3;
wire    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
reg   [21:0] phi_mul_fu_138;
wire   [21:0] next_mul_fu_532_p2;
reg   [10:0] empty_fu_142;
wire   [10:0] empty_61_fu_523_p2;
reg    input_23_we0_local;
wire   [4:0] empty_63_fu_577_p1;
reg    input_23_ce0_local;
reg    input_22_we0_local;
reg    input_22_ce0_local;
reg    input_21_we0_local;
reg    input_21_ce0_local;
reg    input_20_we0_local;
reg    input_20_ce0_local;
reg    input_19_we0_local;
reg    input_19_ce0_local;
reg    input_18_we0_local;
reg    input_18_ce0_local;
reg    input_17_we0_local;
reg    input_17_ce0_local;
reg    input_16_we0_local;
reg    input_16_ce0_local;
reg    input_15_we0_local;
reg    input_15_ce0_local;
reg    input_14_we0_local;
reg    input_14_ce0_local;
reg    input_13_we0_local;
reg    input_13_ce0_local;
reg    input_12_we0_local;
reg    input_12_ce0_local;
reg    input_11_we0_local;
reg    input_11_ce0_local;
reg    input_10_we0_local;
reg    input_10_ce0_local;
reg    input_9_we0_local;
reg    input_9_ce0_local;
reg    input_8_we0_local;
reg    input_8_ce0_local;
reg    input_7_we0_local;
reg    input_7_ce0_local;
reg    input_6_we0_local;
reg    input_6_ce0_local;
reg    input_5_we0_local;
reg    input_5_ce0_local;
reg    input_4_we0_local;
reg    input_4_ce0_local;
reg    input_3_we0_local;
reg    input_3_ce0_local;
reg    input_2_we0_local;
reg    input_2_ce0_local;
reg    input_1_we0_local;
reg    input_1_ce0_local;
reg    input_r_we0_local;
reg    input_r_ce0_local;
reg    input_24_we0_local;
reg    input_24_ce0_local;
wire   [5:0] tmp_fu_538_p4;
wire   [0:0] empty_62_fu_639_p2;
wire   [10:0] next_urem_fu_633_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 phi_urem_fu_134 = 11'd0;
#0 phi_mul_fu_138 = 22'd0;
#0 empty_fu_142 = 11'd0;
#0 ap_done_reg = 1'b0;
end

forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_142 <= 11'd0;
        end else if (((exitcond6079_fu_517_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_fu_142 <= empty_61_fu_523_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_138 <= 22'd0;
        end else if (((exitcond6079_fu_517_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_mul_fu_138 <= next_mul_fu_532_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_134 <= 11'd0;
        end else if (((exitcond6079_fu_517_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_urem_fu_134 <= idx_urem_fu_645_p3;
        end
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_10_ce0_local = 1'b1;
    end else begin
        input_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_10_we0_local = 1'b1;
    end else begin
        input_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_11_ce0_local = 1'b1;
    end else begin
        input_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd11) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_11_we0_local = 1'b1;
    end else begin
        input_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_12_ce0_local = 1'b1;
    end else begin
        input_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_12_we0_local = 1'b1;
    end else begin
        input_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_13_ce0_local = 1'b1;
    end else begin
        input_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd13) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_13_we0_local = 1'b1;
    end else begin
        input_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_14_ce0_local = 1'b1;
    end else begin
        input_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_14_we0_local = 1'b1;
    end else begin
        input_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_15_ce0_local = 1'b1;
    end else begin
        input_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_15_we0_local = 1'b1;
    end else begin
        input_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_16_ce0_local = 1'b1;
    end else begin
        input_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_16_we0_local = 1'b1;
    end else begin
        input_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_17_ce0_local = 1'b1;
    end else begin
        input_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd17) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_17_we0_local = 1'b1;
    end else begin
        input_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_18_ce0_local = 1'b1;
    end else begin
        input_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd18) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_18_we0_local = 1'b1;
    end else begin
        input_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_19_ce0_local = 1'b1;
    end else begin
        input_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd19) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_19_we0_local = 1'b1;
    end else begin
        input_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_ce0_local = 1'b1;
    end else begin
        input_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_we0_local = 1'b1;
    end else begin
        input_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_20_ce0_local = 1'b1;
    end else begin
        input_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd20) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_20_we0_local = 1'b1;
    end else begin
        input_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_21_ce0_local = 1'b1;
    end else begin
        input_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd21) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_21_we0_local = 1'b1;
    end else begin
        input_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_22_ce0_local = 1'b1;
    end else begin
        input_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd22) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_22_we0_local = 1'b1;
    end else begin
        input_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_23_ce0_local = 1'b1;
    end else begin
        input_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd23) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_23_we0_local = 1'b1;
    end else begin
        input_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_24_ce0_local = 1'b1;
    end else begin
        input_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((((((((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd30)) | ((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd31))) | ((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd29))) | ((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd28))) | ((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd27))) | ((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd26))) | ((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd25))) | ((exitcond6079_fu_517_p2 == 1'd0) & (empty_63_fu_577_p1 == 5'd24))))) begin
        input_24_we0_local = 1'b1;
    end else begin
        input_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_2_ce0_local = 1'b1;
    end else begin
        input_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_2_we0_local = 1'b1;
    end else begin
        input_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_3_ce0_local = 1'b1;
    end else begin
        input_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_3_we0_local = 1'b1;
    end else begin
        input_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_4_ce0_local = 1'b1;
    end else begin
        input_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_4_we0_local = 1'b1;
    end else begin
        input_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_5_ce0_local = 1'b1;
    end else begin
        input_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_5_we0_local = 1'b1;
    end else begin
        input_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_6_ce0_local = 1'b1;
    end else begin
        input_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_6_we0_local = 1'b1;
    end else begin
        input_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_7_ce0_local = 1'b1;
    end else begin
        input_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_7_we0_local = 1'b1;
    end else begin
        input_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_8_ce0_local = 1'b1;
    end else begin
        input_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_8_we0_local = 1'b1;
    end else begin
        input_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_9_ce0_local = 1'b1;
    end else begin
        input_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_9_we0_local = 1'b1;
    end else begin
        input_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0_local = 1'b1;
    end else begin
        input_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond6079_fu_517_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (empty_63_fu_577_p1 == 5'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_we0_local = 1'b1;
    end else begin
        input_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign empty_61_fu_523_p2 = (empty_fu_142 + 11'd1);

assign empty_62_fu_639_p2 = ((phi_urem_fu_134 == 11'd24) ? 1'b1 : 1'b0);

assign empty_63_fu_577_p1 = phi_urem_fu_134[4:0];

assign exitcond6079_fu_517_p2 = ((empty_fu_142 == 11'd1250) ? 1'b1 : 1'b0);

assign idx_urem_fu_645_p3 = ((empty_62_fu_639_p2[0:0] == 1'b1) ? 11'd0 : next_urem_fu_633_p2);

assign input_10_address0 = p_cast8_fu_548_p1;

assign input_10_ce0 = input_10_ce0_local;

assign input_10_d0 = 32'd0;

assign input_10_we0 = input_10_we0_local;

assign input_11_address0 = p_cast8_fu_548_p1;

assign input_11_ce0 = input_11_ce0_local;

assign input_11_d0 = 32'd0;

assign input_11_we0 = input_11_we0_local;

assign input_12_address0 = p_cast8_fu_548_p1;

assign input_12_ce0 = input_12_ce0_local;

assign input_12_d0 = 32'd0;

assign input_12_we0 = input_12_we0_local;

assign input_13_address0 = p_cast8_fu_548_p1;

assign input_13_ce0 = input_13_ce0_local;

assign input_13_d0 = 32'd0;

assign input_13_we0 = input_13_we0_local;

assign input_14_address0 = p_cast8_fu_548_p1;

assign input_14_ce0 = input_14_ce0_local;

assign input_14_d0 = 32'd0;

assign input_14_we0 = input_14_we0_local;

assign input_15_address0 = p_cast8_fu_548_p1;

assign input_15_ce0 = input_15_ce0_local;

assign input_15_d0 = 32'd0;

assign input_15_we0 = input_15_we0_local;

assign input_16_address0 = p_cast8_fu_548_p1;

assign input_16_ce0 = input_16_ce0_local;

assign input_16_d0 = 32'd0;

assign input_16_we0 = input_16_we0_local;

assign input_17_address0 = p_cast8_fu_548_p1;

assign input_17_ce0 = input_17_ce0_local;

assign input_17_d0 = 32'd0;

assign input_17_we0 = input_17_we0_local;

assign input_18_address0 = p_cast8_fu_548_p1;

assign input_18_ce0 = input_18_ce0_local;

assign input_18_d0 = 32'd0;

assign input_18_we0 = input_18_we0_local;

assign input_19_address0 = p_cast8_fu_548_p1;

assign input_19_ce0 = input_19_ce0_local;

assign input_19_d0 = 32'd0;

assign input_19_we0 = input_19_we0_local;

assign input_1_address0 = p_cast8_fu_548_p1;

assign input_1_ce0 = input_1_ce0_local;

assign input_1_d0 = 32'd0;

assign input_1_we0 = input_1_we0_local;

assign input_20_address0 = p_cast8_fu_548_p1;

assign input_20_ce0 = input_20_ce0_local;

assign input_20_d0 = 32'd0;

assign input_20_we0 = input_20_we0_local;

assign input_21_address0 = p_cast8_fu_548_p1;

assign input_21_ce0 = input_21_ce0_local;

assign input_21_d0 = 32'd0;

assign input_21_we0 = input_21_we0_local;

assign input_22_address0 = p_cast8_fu_548_p1;

assign input_22_ce0 = input_22_ce0_local;

assign input_22_d0 = 32'd0;

assign input_22_we0 = input_22_we0_local;

assign input_23_address0 = p_cast8_fu_548_p1;

assign input_23_ce0 = input_23_ce0_local;

assign input_23_d0 = 32'd0;

assign input_23_we0 = input_23_we0_local;

assign input_24_address0 = p_cast8_fu_548_p1;

assign input_24_ce0 = input_24_ce0_local;

assign input_24_d0 = 32'd0;

assign input_24_we0 = input_24_we0_local;

assign input_2_address0 = p_cast8_fu_548_p1;

assign input_2_ce0 = input_2_ce0_local;

assign input_2_d0 = 32'd0;

assign input_2_we0 = input_2_we0_local;

assign input_3_address0 = p_cast8_fu_548_p1;

assign input_3_ce0 = input_3_ce0_local;

assign input_3_d0 = 32'd0;

assign input_3_we0 = input_3_we0_local;

assign input_4_address0 = p_cast8_fu_548_p1;

assign input_4_ce0 = input_4_ce0_local;

assign input_4_d0 = 32'd0;

assign input_4_we0 = input_4_we0_local;

assign input_5_address0 = p_cast8_fu_548_p1;

assign input_5_ce0 = input_5_ce0_local;

assign input_5_d0 = 32'd0;

assign input_5_we0 = input_5_we0_local;

assign input_6_address0 = p_cast8_fu_548_p1;

assign input_6_ce0 = input_6_ce0_local;

assign input_6_d0 = 32'd0;

assign input_6_we0 = input_6_we0_local;

assign input_7_address0 = p_cast8_fu_548_p1;

assign input_7_ce0 = input_7_ce0_local;

assign input_7_d0 = 32'd0;

assign input_7_we0 = input_7_we0_local;

assign input_8_address0 = p_cast8_fu_548_p1;

assign input_8_ce0 = input_8_ce0_local;

assign input_8_d0 = 32'd0;

assign input_8_we0 = input_8_we0_local;

assign input_9_address0 = p_cast8_fu_548_p1;

assign input_9_ce0 = input_9_ce0_local;

assign input_9_d0 = 32'd0;

assign input_9_we0 = input_9_we0_local;

assign input_r_address0 = p_cast8_fu_548_p1;

assign input_r_ce0 = input_r_ce0_local;

assign input_r_d0 = 32'd0;

assign input_r_we0 = input_r_we0_local;

assign next_mul_fu_532_p2 = (phi_mul_fu_138 + 22'd2622);

assign next_urem_fu_633_p2 = (phi_urem_fu_134 + 11'd1);

assign p_cast8_fu_548_p1 = tmp_fu_538_p4;

assign tmp_fu_538_p4 = {{phi_mul_fu_138[21:16]}};

endmodule //forward_forward_Pipeline_1
