// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module forward_forward_Pipeline_VITIS_LOOP_179_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_address0,
        output_r_ce0,
        output_r_q0,
        max_conf_index_out,
        max_conf_index_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] output_r_address0;
output   output_r_ce0;
input  [31:0] output_r_q0;
output  [31:0] max_conf_index_out;
output   max_conf_index_out_ap_vld;

reg ap_idle;
reg max_conf_index_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln179_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln179_reg_267;
wire   [2:0] trunc_ln181_2_fu_116_p1;
reg   [2:0] trunc_ln181_2_reg_276;
reg   [2:0] trunc_ln181_2_reg_276_pp0_iter1_reg;
reg   [31:0] max_conf_load_reg_281;
reg   [31:0] conf_reg_288;
wire   [63:0] zext_ln179_fu_111_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] max_conf_fu_44;
wire   [31:0] max_conf_2_fu_214_p3;
reg   [31:0] ap_sig_allocacmp_max_conf_load;
wire    ap_loop_init;
reg   [31:0] max_conf_index_fu_48;
wire   [31:0] max_conf_index_4_fu_223_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [3:0] max_conf_index_1_fu_52;
wire   [3:0] add_ln179_fu_105_p2;
reg   [3:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0_01001;
reg    output_r_ce0_local;
wire   [31:0] bitcast_ln181_fu_132_p1;
wire   [31:0] bitcast_ln181_1_fu_149_p1;
wire   [7:0] tmp_2_fu_135_p4;
wire   [22:0] trunc_ln181_fu_145_p1;
wire   [0:0] icmp_ln181_1_fu_172_p2;
wire   [0:0] icmp_ln181_fu_166_p2;
wire   [7:0] tmp_3_fu_152_p4;
wire   [22:0] trunc_ln181_1_fu_162_p1;
wire   [0:0] icmp_ln181_3_fu_190_p2;
wire   [0:0] icmp_ln181_2_fu_184_p2;
wire   [0:0] grp_fu_76_p2;
wire   [0:0] or_ln181_fu_178_p2;
wire   [0:0] and_ln181_fu_202_p2;
wire   [0:0] or_ln181_1_fu_196_p2;
wire   [0:0] and_ln181_1_fu_208_p2;
wire   [31:0] zext_ln181_fu_220_p1;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 max_conf_fu_44 = 32'd0;
#0 max_conf_index_fu_48 = 32'd0;
#0 max_conf_index_1_fu_52 = 4'd0;
#0 ap_done_reg = 1'b0;
end

forward_fcmp_32ns_32ns_1_2_no_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_x_U343(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(output_r_q0),
    .din1(ap_sig_allocacmp_max_conf_load),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_76_p2)
);

forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_conf_fu_44 <= 32'd3287941120;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            max_conf_fu_44 <= max_conf_2_fu_214_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln179_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            max_conf_index_1_fu_52 <= add_ln179_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            max_conf_index_1_fu_52 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_conf_index_fu_48 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            max_conf_index_fu_48 <= max_conf_index_4_fu_223_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        conf_reg_288 <= output_r_q0;
        icmp_ln179_reg_267 <= icmp_ln179_fu_99_p2;
        max_conf_load_reg_281 <= ap_sig_allocacmp_max_conf_load;
        trunc_ln181_2_reg_276 <= trunc_ln181_2_fu_116_p1;
        trunc_ln181_2_reg_276_pp0_iter1_reg <= trunc_ln181_2_reg_276;
    end
end

always @ (*) begin
    if (((icmp_ln179_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = max_conf_index_1_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_max_conf_load = max_conf_2_fu_214_p3;
    end else begin
        ap_sig_allocacmp_max_conf_load = max_conf_fu_44;
    end
end

always @ (*) begin
    if (((icmp_ln179_reg_267 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        max_conf_index_out_ap_vld = 1'b1;
    end else begin
        max_conf_index_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln179_fu_105_p2 = (ap_sig_allocacmp_i + 4'd1);

assign and_ln181_1_fu_208_p2 = (or_ln181_1_fu_196_p2 & and_ln181_fu_202_p2);

assign and_ln181_fu_202_p2 = (or_ln181_fu_178_p2 & grp_fu_76_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln181_1_fu_149_p1 = max_conf_load_reg_281;

assign bitcast_ln181_fu_132_p1 = conf_reg_288;

assign icmp_ln179_fu_99_p2 = ((ap_sig_allocacmp_i == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln181_1_fu_172_p2 = ((trunc_ln181_fu_145_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln181_2_fu_184_p2 = ((tmp_3_fu_152_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln181_3_fu_190_p2 = ((trunc_ln181_1_fu_162_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln181_fu_166_p2 = ((tmp_2_fu_135_p4 != 8'd255) ? 1'b1 : 1'b0);

assign max_conf_2_fu_214_p3 = ((and_ln181_1_fu_208_p2[0:0] == 1'b1) ? conf_reg_288 : max_conf_load_reg_281);

assign max_conf_index_4_fu_223_p3 = ((and_ln181_1_fu_208_p2[0:0] == 1'b1) ? zext_ln181_fu_220_p1 : max_conf_index_fu_48);

assign max_conf_index_out = max_conf_index_fu_48;

assign or_ln181_1_fu_196_p2 = (icmp_ln181_3_fu_190_p2 | icmp_ln181_2_fu_184_p2);

assign or_ln181_fu_178_p2 = (icmp_ln181_fu_166_p2 | icmp_ln181_1_fu_172_p2);

assign output_r_address0 = zext_ln179_fu_111_p1;

assign output_r_ce0 = output_r_ce0_local;

assign tmp_2_fu_135_p4 = {{bitcast_ln181_fu_132_p1[30:23]}};

assign tmp_3_fu_152_p4 = {{bitcast_ln181_1_fu_149_p1[30:23]}};

assign trunc_ln181_1_fu_162_p1 = bitcast_ln181_1_fu_149_p1[22:0];

assign trunc_ln181_2_fu_116_p1 = ap_sig_allocacmp_i[2:0];

assign trunc_ln181_fu_145_p1 = bitcast_ln181_fu_132_p1[22:0];

assign zext_ln179_fu_111_p1 = ap_sig_allocacmp_i;

assign zext_ln181_fu_220_p1 = trunc_ln181_2_reg_276_pp0_iter1_reg;

endmodule //forward_forward_Pipeline_VITIS_LOOP_179_6
