// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module forward_generic_tanh_float_s (
        ap_clk,
        ap_rst,
        t_in,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] t_in;
output  [31:0] ap_return;

reg   [31:0] expx_reg_58;
reg   [31:0] expx_reg_58_pp0_iter24_reg;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] expx_reg_58_pp0_iter25_reg;
reg   [31:0] expx_reg_58_pp0_iter26_reg;
reg   [31:0] resultf_3_reg_72;
wire   [31:0] grp_fu_130_p2;
reg   [31:0] reg_152;
reg   [0:0] icmp_ln36_reg_412;
reg   [0:0] icmp_ln36_reg_412_pp0_iter34_reg;
reg   [0:0] icmp_ln45_reg_416;
reg   [0:0] icmp_ln45_reg_416_pp0_iter34_reg;
reg   [0:0] and_ln46_reg_425;
reg   [0:0] and_ln46_reg_425_pp0_iter34_reg;
reg   [0:0] and_ln51_reg_439;
reg   [0:0] and_ln51_reg_439_pp0_iter34_reg;
reg   [0:0] icmp_ln54_reg_443;
reg   [0:0] icmp_ln54_reg_443_pp0_iter34_reg;
reg    ap_predicate_pred44_state37;
reg    ap_predicate_pred53_state37;
reg   [0:0] din_sign_reg_387;
reg   [0:0] din_sign_reg_387_pp0_iter1_reg;
reg   [0:0] din_sign_reg_387_pp0_iter2_reg;
reg   [0:0] din_sign_reg_387_pp0_iter3_reg;
reg   [0:0] din_sign_reg_387_pp0_iter4_reg;
reg   [0:0] din_sign_reg_387_pp0_iter5_reg;
reg   [0:0] din_sign_reg_387_pp0_iter6_reg;
reg   [0:0] din_sign_reg_387_pp0_iter7_reg;
reg   [0:0] din_sign_reg_387_pp0_iter8_reg;
reg   [0:0] din_sign_reg_387_pp0_iter9_reg;
reg   [0:0] din_sign_reg_387_pp0_iter10_reg;
reg   [0:0] din_sign_reg_387_pp0_iter11_reg;
reg   [0:0] din_sign_reg_387_pp0_iter12_reg;
reg   [0:0] din_sign_reg_387_pp0_iter13_reg;
reg   [0:0] din_sign_reg_387_pp0_iter14_reg;
reg   [0:0] din_sign_reg_387_pp0_iter15_reg;
reg   [0:0] din_sign_reg_387_pp0_iter16_reg;
reg   [0:0] din_sign_reg_387_pp0_iter17_reg;
reg   [0:0] din_sign_reg_387_pp0_iter18_reg;
reg   [0:0] din_sign_reg_387_pp0_iter19_reg;
reg   [0:0] din_sign_reg_387_pp0_iter20_reg;
reg   [0:0] din_sign_reg_387_pp0_iter21_reg;
reg   [0:0] din_sign_reg_387_pp0_iter22_reg;
reg   [0:0] din_sign_reg_387_pp0_iter23_reg;
reg   [0:0] din_sign_reg_387_pp0_iter24_reg;
reg   [0:0] din_sign_reg_387_pp0_iter25_reg;
reg   [0:0] din_sign_reg_387_pp0_iter26_reg;
reg   [0:0] din_sign_reg_387_pp0_iter27_reg;
reg   [0:0] din_sign_reg_387_pp0_iter28_reg;
reg   [0:0] din_sign_reg_387_pp0_iter29_reg;
reg   [0:0] din_sign_reg_387_pp0_iter30_reg;
reg   [0:0] din_sign_reg_387_pp0_iter31_reg;
reg   [0:0] din_sign_reg_387_pp0_iter32_reg;
reg   [0:0] din_sign_reg_387_pp0_iter33_reg;
reg   [0:0] din_sign_reg_387_pp0_iter34_reg;
reg   [0:0] din_sign_reg_387_pp0_iter35_reg;
reg   [0:0] din_sign_reg_387_pp0_iter36_reg;
reg   [0:0] din_sign_reg_387_pp0_iter37_reg;
reg   [0:0] din_sign_reg_387_pp0_iter38_reg;
reg   [0:0] din_sign_reg_387_pp0_iter39_reg;
reg   [0:0] din_sign_reg_387_pp0_iter40_reg;
wire   [7:0] din_exp_fu_170_p3;
reg   [7:0] din_exp_reg_392;
wire   [30:0] t_fu_182_p1;
reg   [30:0] t_reg_397;
wire   [31:0] abst_in_fu_190_p1;
reg   [31:0] abst_in_reg_402;
reg   [31:0] abst_in_reg_402_pp0_iter1_reg;
reg   [31:0] abst_in_reg_402_pp0_iter2_reg;
reg   [31:0] abst_in_reg_402_pp0_iter3_reg;
wire   [0:0] icmp_ln36_fu_196_p2;
reg   [0:0] icmp_ln36_reg_412_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter2_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter3_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter4_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter5_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter6_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter7_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter8_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter9_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter10_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter11_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter12_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter13_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter14_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter15_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter16_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter17_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter18_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter19_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter20_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter21_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter22_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter23_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter24_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter25_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter26_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter27_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter28_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter29_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter30_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter31_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter32_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter33_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter35_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter36_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter37_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter38_reg;
reg   [0:0] icmp_ln36_reg_412_pp0_iter39_reg;
wire   [0:0] icmp_ln45_fu_202_p2;
reg   [0:0] icmp_ln45_reg_416_pp0_iter1_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter2_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter3_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter4_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter5_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter6_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter7_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter8_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter9_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter10_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter11_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter12_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter13_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter14_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter15_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter16_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter17_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter18_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter19_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter20_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter21_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter22_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter23_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter24_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter25_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter26_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter27_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter28_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter29_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter30_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter31_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter32_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter33_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter35_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter36_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter37_reg;
reg   [0:0] icmp_ln45_reg_416_pp0_iter38_reg;
wire   [0:0] icmp_ln46_1_fu_214_p2;
reg   [0:0] icmp_ln46_1_reg_420;
wire   [0:0] and_ln46_fu_220_p2;
reg   [0:0] and_ln46_reg_425_pp0_iter1_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter2_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter3_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter4_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter5_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter6_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter7_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter8_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter9_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter10_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter11_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter12_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter13_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter14_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter15_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter16_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter17_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter18_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter19_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter20_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter21_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter22_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter23_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter24_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter25_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter26_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter27_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter28_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter29_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter30_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter31_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter32_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter33_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter35_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter36_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter37_reg;
reg   [0:0] and_ln46_reg_425_pp0_iter38_reg;
wire   [0:0] icmp_ln51_fu_236_p2;
reg   [0:0] icmp_ln51_reg_429;
wire   [0:0] icmp_ln38_fu_242_p2;
reg   [0:0] icmp_ln38_reg_434;
reg   [0:0] icmp_ln38_reg_434_pp0_iter1_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter2_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter3_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter4_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter5_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter6_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter7_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter8_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter9_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter10_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter11_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter12_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter13_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter14_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter15_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter16_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter17_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter18_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter19_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter20_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter21_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter22_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter23_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter24_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter25_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter26_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter27_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter28_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter29_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter30_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter31_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter32_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter33_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter34_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter35_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter36_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter37_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter38_reg;
reg   [0:0] icmp_ln38_reg_434_pp0_iter39_reg;
wire   [0:0] and_ln51_fu_252_p2;
reg   [0:0] and_ln51_reg_439_pp0_iter2_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter3_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter4_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter5_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter6_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter7_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter8_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter9_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter10_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter11_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter12_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter13_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter14_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter15_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter16_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter17_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter18_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter19_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter20_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter21_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter22_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter23_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter24_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter25_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter26_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter27_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter28_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter29_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter30_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter31_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter32_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter33_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter35_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter36_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter37_reg;
reg   [0:0] and_ln51_reg_439_pp0_iter38_reg;
wire   [0:0] icmp_ln54_fu_258_p2;
reg   [0:0] icmp_ln54_reg_443_pp0_iter2_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter3_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter4_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter5_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter6_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter7_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter8_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter9_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter10_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter11_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter12_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter13_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter14_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter15_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter16_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter17_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter18_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter19_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter20_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter21_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter22_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter23_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter24_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter25_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter26_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter27_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter28_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter29_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter30_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter31_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter32_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter33_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter35_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter36_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter37_reg;
reg   [0:0] icmp_ln54_reg_443_pp0_iter38_reg;
wire   [31:0] grp_fu_101_p2;
reg   [31:0] add_reg_453;
wire   [31:0] x_3_fu_275_p3;
reg   [31:0] x_3_reg_458;
wire   [0:0] icmp_ln9_fu_293_p2;
reg   [0:0] icmp_ln9_reg_465;
reg   [0:0] icmp_ln9_reg_465_pp0_iter6_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter7_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter8_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter9_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter10_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter11_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter12_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter13_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter14_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter15_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter16_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter17_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter18_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter19_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter20_reg;
reg   [0:0] icmp_ln9_reg_465_pp0_iter21_reg;
wire   [0:0] icmp_ln10_fu_299_p2;
reg   [0:0] icmp_ln10_reg_469;
reg   [0:0] icmp_ln10_reg_469_pp0_iter6_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter7_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter8_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter9_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter10_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter11_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter12_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter13_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter14_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter15_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter16_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter17_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter18_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter19_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter20_reg;
reg   [0:0] icmp_ln10_reg_469_pp0_iter21_reg;
wire   [63:0] grp_fu_139_p1;
reg   [63:0] xd_reg_473;
wire   [31:0] grp_fu_126_p2;
reg   [31:0] resultf_reg_478;
wire   [63:0] grp_exp_generic_double_s_fu_90_ap_return;
reg   [63:0] tmp_5_reg_483;
wire    ap_block_pp0_stage0_11001_ignoreCallOp108;
wire   [63:0] grp_fu_147_p2;
reg   [63:0] sub_i_reg_488;
wire   [31:0] grp_fu_114_p2;
reg   [31:0] add2_reg_493;
wire   [0:0] xor_ln66_fu_317_p2;
reg   [0:0] xor_ln66_reg_498;
wire   [30:0] trunc_ln66_fu_323_p1;
reg   [30:0] trunc_ln66_reg_503;
wire   [31:0] bitcast_ln66_1_fu_333_p1;
reg    grp_exp_generic_double_s_fu_90_ap_ce;
reg    ap_predicate_op98_call_state8;
wire    ap_block_pp0_stage0_11001_ignoreCallOp98;
wire   [31:0] grp_fu_135_p1;
reg   [31:0] ap_phi_reg_pp0_iter23_expx_reg_58;
reg    ap_predicate_pred614_state24;
wire   [31:0] ap_phi_reg_pp0_iter0_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter1_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter2_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter3_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter4_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter5_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter6_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter7_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter8_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter9_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter10_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter11_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter12_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter13_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter14_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter15_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter16_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter17_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter18_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter19_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter20_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter21_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter22_expx_reg_58;
wire   [31:0] ap_phi_reg_pp0_iter0_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter1_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter2_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter3_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter4_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter5_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter6_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter7_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter8_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter9_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter10_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter11_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter12_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter13_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter14_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter15_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter16_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter17_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter18_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter19_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter20_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter21_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter22_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter23_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter24_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter25_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter26_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter27_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter28_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter29_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter30_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter31_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter32_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter33_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter34_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter35_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter36_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter37_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter38_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter39_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter40_resultf_3_reg_72;
reg    ap_predicate_pred731_state38;
wire   [31:0] grp_fu_120_p2;
reg    ap_predicate_pred744_state41;
wire   [31:0] select_ln38_fu_338_p3;
wire    ap_block_pp0_stage0_ignoreCallOp98;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_106_p0;
reg   [31:0] grp_fu_130_p0;
reg    ap_predicate_pred800_state29;
reg    ap_predicate_pred805_state29;
wire   [31:0] data_fu_158_p1;
wire   [31:0] zext_ln313_fu_186_p1;
wire   [22:0] din_sig_fu_178_p1;
wire   [0:0] icmp_ln46_fu_208_p2;
wire   [7:0] tmp_fu_226_p4;
wire   [0:0] or_ln51_fu_248_p2;
wire   [0:0] grp_fu_142_p2;
wire   [31:0] or_ln_fu_263_p3;
wire   [31:0] grp_fu_106_p2;
wire   [31:0] grp_fu_110_p2;
wire   [31:0] data_1_fu_282_p1;
wire   [7:0] xs_exp_1_fu_285_p3;
wire   [31:0] bitcast_ln66_fu_305_p1;
wire   [0:0] bit_sel_fu_309_p3;
wire   [31:0] xor_ln_fu_327_p3;
wire   [31:0] bitcast_ln83_fu_346_p1;
wire   [0:0] bit_sel1_fu_350_p3;
wire   [0:0] xor_ln83_fu_358_p2;
wire   [30:0] trunc_ln83_fu_364_p1;
wire   [31:0] xor_ln1_fu_368_p3;
wire   [31:0] bitcast_ln83_1_fu_376_p1;
wire    ap_block_pp0_stage0_00001;
reg   [31:0] t_in_int_reg;
reg    ap_condition_767;
reg    ap_condition_668;
reg    ap_condition_673;
reg    ap_condition_721;
wire    ap_ce_reg;

forward_exp_generic_double_s grp_exp_generic_double_s_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(xd_reg_473),
    .ap_return(grp_exp_generic_double_s_fu_90_ap_return),
    .ap_ce(grp_exp_generic_double_s_fu_90_ap_ce)
);

forward_fadd_32ns_32ns_32_4_full_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_x_U252(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_fu_190_p1),
    .din1(32'd1065353216),
    .ce(1'b1),
    .dout(grp_fu_101_p2)
);

forward_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U253(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_106_p0),
    .din1(abst_in_reg_402),
    .ce(1'b1),
    .dout(grp_fu_106_p2)
);

forward_fadd_32ns_32ns_32_4_full_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_x_U254(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_reg_402),
    .din1(abst_in_reg_402),
    .ce(1'b1),
    .dout(grp_fu_110_p2)
);

forward_fadd_32ns_32ns_32_4_full_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_x_U255(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(expx_reg_58),
    .din1(32'd1073741824),
    .ce(1'b1),
    .dout(grp_fu_114_p2)
);

forward_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U256(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(reg_152),
    .ce(1'b1),
    .dout(grp_fu_120_p2)
);

forward_fmul_32ns_32ns_32_3_max_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_x_U257(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_reg_402_pp0_iter3_reg),
    .din1(add_reg_453),
    .ce(1'b1),
    .dout(grp_fu_126_p2)
);

forward_fdiv_32ns_32ns_32_9_no_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_x_U258(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_130_p0),
    .din1(add2_reg_493),
    .ce(1'b1),
    .dout(grp_fu_130_p2)
);

forward_fptrunc_64ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
fptrunc_64ns_32_2_no_dsp_1_U259(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_i_reg_488),
    .ce(1'b1),
    .dout(grp_fu_135_p1)
);

forward_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U260(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_3_reg_458),
    .ce(1'b1),
    .dout(grp_fu_139_p1)
);

forward_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U261(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_fu_190_p1),
    .din1(32'd1102053376),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_142_p2)
);

forward_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U262(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_reg_483),
    .din1(64'd13830554455654793216),
    .ce(1'b1),
    .dout(grp_fu_147_p2)
);

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_767)) begin
            ap_phi_reg_pp0_iter2_resultf_3_reg_72 <= 32'd1065353216;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_resultf_3_reg_72 <= ap_phi_reg_pp0_iter1_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((ap_predicate_pred731_state38 == 1'b1)) begin
            ap_phi_reg_pp0_iter38_resultf_3_reg_72 <= reg_152;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter38_resultf_3_reg_72 <= ap_phi_reg_pp0_iter37_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_673)) begin
            ap_phi_reg_pp0_iter6_expx_reg_58 <= x_3_reg_458;
        end else if ((1'b1 == ap_condition_668)) begin
            ap_phi_reg_pp0_iter6_expx_reg_58 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter6_expx_reg_58 <= ap_phi_reg_pp0_iter5_expx_reg_58;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_721)) begin
            ap_phi_reg_pp0_iter8_resultf_3_reg_72 <= resultf_reg_478;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter8_resultf_3_reg_72 <= ap_phi_reg_pp0_iter7_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((ap_predicate_pred614_state24 == 1'b1)) begin
            expx_reg_58 <= grp_fu_135_p1;
        end else if ((1'b1 == 1'b1)) begin
            expx_reg_58 <= ap_phi_reg_pp0_iter23_expx_reg_58;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((icmp_ln36_reg_412_pp0_iter39_reg == 1'd1)) begin
            resultf_3_reg_72 <= select_ln38_fu_338_p3;
        end else if ((ap_predicate_pred744_state41 == 1'b1)) begin
            resultf_3_reg_72 <= grp_fu_120_p2;
        end else if ((1'b1 == 1'b1)) begin
            resultf_3_reg_72 <= ap_phi_reg_pp0_iter40_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    t_in_int_reg <= t_in;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        abst_in_reg_402[30 : 0] <= abst_in_fu_190_p1[30 : 0];
        abst_in_reg_402_pp0_iter1_reg[30 : 0] <= abst_in_reg_402[30 : 0];
        abst_in_reg_402_pp0_iter2_reg[30 : 0] <= abst_in_reg_402_pp0_iter1_reg[30 : 0];
        abst_in_reg_402_pp0_iter3_reg[30 : 0] <= abst_in_reg_402_pp0_iter2_reg[30 : 0];
        add2_reg_493 <= grp_fu_114_p2;
        add_reg_453 <= grp_fu_101_p2;
        and_ln46_reg_425 <= and_ln46_fu_220_p2;
        and_ln46_reg_425_pp0_iter10_reg <= and_ln46_reg_425_pp0_iter9_reg;
        and_ln46_reg_425_pp0_iter11_reg <= and_ln46_reg_425_pp0_iter10_reg;
        and_ln46_reg_425_pp0_iter12_reg <= and_ln46_reg_425_pp0_iter11_reg;
        and_ln46_reg_425_pp0_iter13_reg <= and_ln46_reg_425_pp0_iter12_reg;
        and_ln46_reg_425_pp0_iter14_reg <= and_ln46_reg_425_pp0_iter13_reg;
        and_ln46_reg_425_pp0_iter15_reg <= and_ln46_reg_425_pp0_iter14_reg;
        and_ln46_reg_425_pp0_iter16_reg <= and_ln46_reg_425_pp0_iter15_reg;
        and_ln46_reg_425_pp0_iter17_reg <= and_ln46_reg_425_pp0_iter16_reg;
        and_ln46_reg_425_pp0_iter18_reg <= and_ln46_reg_425_pp0_iter17_reg;
        and_ln46_reg_425_pp0_iter19_reg <= and_ln46_reg_425_pp0_iter18_reg;
        and_ln46_reg_425_pp0_iter1_reg <= and_ln46_reg_425;
        and_ln46_reg_425_pp0_iter20_reg <= and_ln46_reg_425_pp0_iter19_reg;
        and_ln46_reg_425_pp0_iter21_reg <= and_ln46_reg_425_pp0_iter20_reg;
        and_ln46_reg_425_pp0_iter22_reg <= and_ln46_reg_425_pp0_iter21_reg;
        and_ln46_reg_425_pp0_iter23_reg <= and_ln46_reg_425_pp0_iter22_reg;
        and_ln46_reg_425_pp0_iter24_reg <= and_ln46_reg_425_pp0_iter23_reg;
        and_ln46_reg_425_pp0_iter25_reg <= and_ln46_reg_425_pp0_iter24_reg;
        and_ln46_reg_425_pp0_iter26_reg <= and_ln46_reg_425_pp0_iter25_reg;
        and_ln46_reg_425_pp0_iter27_reg <= and_ln46_reg_425_pp0_iter26_reg;
        and_ln46_reg_425_pp0_iter28_reg <= and_ln46_reg_425_pp0_iter27_reg;
        and_ln46_reg_425_pp0_iter29_reg <= and_ln46_reg_425_pp0_iter28_reg;
        and_ln46_reg_425_pp0_iter2_reg <= and_ln46_reg_425_pp0_iter1_reg;
        and_ln46_reg_425_pp0_iter30_reg <= and_ln46_reg_425_pp0_iter29_reg;
        and_ln46_reg_425_pp0_iter31_reg <= and_ln46_reg_425_pp0_iter30_reg;
        and_ln46_reg_425_pp0_iter32_reg <= and_ln46_reg_425_pp0_iter31_reg;
        and_ln46_reg_425_pp0_iter33_reg <= and_ln46_reg_425_pp0_iter32_reg;
        and_ln46_reg_425_pp0_iter34_reg <= and_ln46_reg_425_pp0_iter33_reg;
        and_ln46_reg_425_pp0_iter35_reg <= and_ln46_reg_425_pp0_iter34_reg;
        and_ln46_reg_425_pp0_iter36_reg <= and_ln46_reg_425_pp0_iter35_reg;
        and_ln46_reg_425_pp0_iter37_reg <= and_ln46_reg_425_pp0_iter36_reg;
        and_ln46_reg_425_pp0_iter38_reg <= and_ln46_reg_425_pp0_iter37_reg;
        and_ln46_reg_425_pp0_iter3_reg <= and_ln46_reg_425_pp0_iter2_reg;
        and_ln46_reg_425_pp0_iter4_reg <= and_ln46_reg_425_pp0_iter3_reg;
        and_ln46_reg_425_pp0_iter5_reg <= and_ln46_reg_425_pp0_iter4_reg;
        and_ln46_reg_425_pp0_iter6_reg <= and_ln46_reg_425_pp0_iter5_reg;
        and_ln46_reg_425_pp0_iter7_reg <= and_ln46_reg_425_pp0_iter6_reg;
        and_ln46_reg_425_pp0_iter8_reg <= and_ln46_reg_425_pp0_iter7_reg;
        and_ln46_reg_425_pp0_iter9_reg <= and_ln46_reg_425_pp0_iter8_reg;
        and_ln51_reg_439 <= and_ln51_fu_252_p2;
        and_ln51_reg_439_pp0_iter10_reg <= and_ln51_reg_439_pp0_iter9_reg;
        and_ln51_reg_439_pp0_iter11_reg <= and_ln51_reg_439_pp0_iter10_reg;
        and_ln51_reg_439_pp0_iter12_reg <= and_ln51_reg_439_pp0_iter11_reg;
        and_ln51_reg_439_pp0_iter13_reg <= and_ln51_reg_439_pp0_iter12_reg;
        and_ln51_reg_439_pp0_iter14_reg <= and_ln51_reg_439_pp0_iter13_reg;
        and_ln51_reg_439_pp0_iter15_reg <= and_ln51_reg_439_pp0_iter14_reg;
        and_ln51_reg_439_pp0_iter16_reg <= and_ln51_reg_439_pp0_iter15_reg;
        and_ln51_reg_439_pp0_iter17_reg <= and_ln51_reg_439_pp0_iter16_reg;
        and_ln51_reg_439_pp0_iter18_reg <= and_ln51_reg_439_pp0_iter17_reg;
        and_ln51_reg_439_pp0_iter19_reg <= and_ln51_reg_439_pp0_iter18_reg;
        and_ln51_reg_439_pp0_iter20_reg <= and_ln51_reg_439_pp0_iter19_reg;
        and_ln51_reg_439_pp0_iter21_reg <= and_ln51_reg_439_pp0_iter20_reg;
        and_ln51_reg_439_pp0_iter22_reg <= and_ln51_reg_439_pp0_iter21_reg;
        and_ln51_reg_439_pp0_iter23_reg <= and_ln51_reg_439_pp0_iter22_reg;
        and_ln51_reg_439_pp0_iter24_reg <= and_ln51_reg_439_pp0_iter23_reg;
        and_ln51_reg_439_pp0_iter25_reg <= and_ln51_reg_439_pp0_iter24_reg;
        and_ln51_reg_439_pp0_iter26_reg <= and_ln51_reg_439_pp0_iter25_reg;
        and_ln51_reg_439_pp0_iter27_reg <= and_ln51_reg_439_pp0_iter26_reg;
        and_ln51_reg_439_pp0_iter28_reg <= and_ln51_reg_439_pp0_iter27_reg;
        and_ln51_reg_439_pp0_iter29_reg <= and_ln51_reg_439_pp0_iter28_reg;
        and_ln51_reg_439_pp0_iter2_reg <= and_ln51_reg_439;
        and_ln51_reg_439_pp0_iter30_reg <= and_ln51_reg_439_pp0_iter29_reg;
        and_ln51_reg_439_pp0_iter31_reg <= and_ln51_reg_439_pp0_iter30_reg;
        and_ln51_reg_439_pp0_iter32_reg <= and_ln51_reg_439_pp0_iter31_reg;
        and_ln51_reg_439_pp0_iter33_reg <= and_ln51_reg_439_pp0_iter32_reg;
        and_ln51_reg_439_pp0_iter34_reg <= and_ln51_reg_439_pp0_iter33_reg;
        and_ln51_reg_439_pp0_iter35_reg <= and_ln51_reg_439_pp0_iter34_reg;
        and_ln51_reg_439_pp0_iter36_reg <= and_ln51_reg_439_pp0_iter35_reg;
        and_ln51_reg_439_pp0_iter37_reg <= and_ln51_reg_439_pp0_iter36_reg;
        and_ln51_reg_439_pp0_iter38_reg <= and_ln51_reg_439_pp0_iter37_reg;
        and_ln51_reg_439_pp0_iter3_reg <= and_ln51_reg_439_pp0_iter2_reg;
        and_ln51_reg_439_pp0_iter4_reg <= and_ln51_reg_439_pp0_iter3_reg;
        and_ln51_reg_439_pp0_iter5_reg <= and_ln51_reg_439_pp0_iter4_reg;
        and_ln51_reg_439_pp0_iter6_reg <= and_ln51_reg_439_pp0_iter5_reg;
        and_ln51_reg_439_pp0_iter7_reg <= and_ln51_reg_439_pp0_iter6_reg;
        and_ln51_reg_439_pp0_iter8_reg <= and_ln51_reg_439_pp0_iter7_reg;
        and_ln51_reg_439_pp0_iter9_reg <= and_ln51_reg_439_pp0_iter8_reg;
        ap_phi_reg_pp0_iter10_expx_reg_58 <= ap_phi_reg_pp0_iter9_expx_reg_58;
        ap_phi_reg_pp0_iter10_resultf_3_reg_72 <= ap_phi_reg_pp0_iter9_resultf_3_reg_72;
        ap_phi_reg_pp0_iter11_expx_reg_58 <= ap_phi_reg_pp0_iter10_expx_reg_58;
        ap_phi_reg_pp0_iter11_resultf_3_reg_72 <= ap_phi_reg_pp0_iter10_resultf_3_reg_72;
        ap_phi_reg_pp0_iter12_expx_reg_58 <= ap_phi_reg_pp0_iter11_expx_reg_58;
        ap_phi_reg_pp0_iter12_resultf_3_reg_72 <= ap_phi_reg_pp0_iter11_resultf_3_reg_72;
        ap_phi_reg_pp0_iter13_expx_reg_58 <= ap_phi_reg_pp0_iter12_expx_reg_58;
        ap_phi_reg_pp0_iter13_resultf_3_reg_72 <= ap_phi_reg_pp0_iter12_resultf_3_reg_72;
        ap_phi_reg_pp0_iter14_expx_reg_58 <= ap_phi_reg_pp0_iter13_expx_reg_58;
        ap_phi_reg_pp0_iter14_resultf_3_reg_72 <= ap_phi_reg_pp0_iter13_resultf_3_reg_72;
        ap_phi_reg_pp0_iter15_expx_reg_58 <= ap_phi_reg_pp0_iter14_expx_reg_58;
        ap_phi_reg_pp0_iter15_resultf_3_reg_72 <= ap_phi_reg_pp0_iter14_resultf_3_reg_72;
        ap_phi_reg_pp0_iter16_expx_reg_58 <= ap_phi_reg_pp0_iter15_expx_reg_58;
        ap_phi_reg_pp0_iter16_resultf_3_reg_72 <= ap_phi_reg_pp0_iter15_resultf_3_reg_72;
        ap_phi_reg_pp0_iter17_expx_reg_58 <= ap_phi_reg_pp0_iter16_expx_reg_58;
        ap_phi_reg_pp0_iter17_resultf_3_reg_72 <= ap_phi_reg_pp0_iter16_resultf_3_reg_72;
        ap_phi_reg_pp0_iter18_expx_reg_58 <= ap_phi_reg_pp0_iter17_expx_reg_58;
        ap_phi_reg_pp0_iter18_resultf_3_reg_72 <= ap_phi_reg_pp0_iter17_resultf_3_reg_72;
        ap_phi_reg_pp0_iter19_expx_reg_58 <= ap_phi_reg_pp0_iter18_expx_reg_58;
        ap_phi_reg_pp0_iter19_resultf_3_reg_72 <= ap_phi_reg_pp0_iter18_resultf_3_reg_72;
        ap_phi_reg_pp0_iter1_expx_reg_58 <= ap_phi_reg_pp0_iter0_expx_reg_58;
        ap_phi_reg_pp0_iter1_resultf_3_reg_72 <= ap_phi_reg_pp0_iter0_resultf_3_reg_72;
        ap_phi_reg_pp0_iter20_expx_reg_58 <= ap_phi_reg_pp0_iter19_expx_reg_58;
        ap_phi_reg_pp0_iter20_resultf_3_reg_72 <= ap_phi_reg_pp0_iter19_resultf_3_reg_72;
        ap_phi_reg_pp0_iter21_expx_reg_58 <= ap_phi_reg_pp0_iter20_expx_reg_58;
        ap_phi_reg_pp0_iter21_resultf_3_reg_72 <= ap_phi_reg_pp0_iter20_resultf_3_reg_72;
        ap_phi_reg_pp0_iter22_expx_reg_58 <= ap_phi_reg_pp0_iter21_expx_reg_58;
        ap_phi_reg_pp0_iter22_resultf_3_reg_72 <= ap_phi_reg_pp0_iter21_resultf_3_reg_72;
        ap_phi_reg_pp0_iter23_expx_reg_58 <= ap_phi_reg_pp0_iter22_expx_reg_58;
        ap_phi_reg_pp0_iter23_resultf_3_reg_72 <= ap_phi_reg_pp0_iter22_resultf_3_reg_72;
        ap_phi_reg_pp0_iter24_resultf_3_reg_72 <= ap_phi_reg_pp0_iter23_resultf_3_reg_72;
        ap_phi_reg_pp0_iter25_resultf_3_reg_72 <= ap_phi_reg_pp0_iter24_resultf_3_reg_72;
        ap_phi_reg_pp0_iter26_resultf_3_reg_72 <= ap_phi_reg_pp0_iter25_resultf_3_reg_72;
        ap_phi_reg_pp0_iter27_resultf_3_reg_72 <= ap_phi_reg_pp0_iter26_resultf_3_reg_72;
        ap_phi_reg_pp0_iter28_resultf_3_reg_72 <= ap_phi_reg_pp0_iter27_resultf_3_reg_72;
        ap_phi_reg_pp0_iter29_resultf_3_reg_72 <= ap_phi_reg_pp0_iter28_resultf_3_reg_72;
        ap_phi_reg_pp0_iter2_expx_reg_58 <= ap_phi_reg_pp0_iter1_expx_reg_58;
        ap_phi_reg_pp0_iter30_resultf_3_reg_72 <= ap_phi_reg_pp0_iter29_resultf_3_reg_72;
        ap_phi_reg_pp0_iter31_resultf_3_reg_72 <= ap_phi_reg_pp0_iter30_resultf_3_reg_72;
        ap_phi_reg_pp0_iter32_resultf_3_reg_72 <= ap_phi_reg_pp0_iter31_resultf_3_reg_72;
        ap_phi_reg_pp0_iter33_resultf_3_reg_72 <= ap_phi_reg_pp0_iter32_resultf_3_reg_72;
        ap_phi_reg_pp0_iter34_resultf_3_reg_72 <= ap_phi_reg_pp0_iter33_resultf_3_reg_72;
        ap_phi_reg_pp0_iter35_resultf_3_reg_72 <= ap_phi_reg_pp0_iter34_resultf_3_reg_72;
        ap_phi_reg_pp0_iter36_resultf_3_reg_72 <= ap_phi_reg_pp0_iter35_resultf_3_reg_72;
        ap_phi_reg_pp0_iter37_resultf_3_reg_72 <= ap_phi_reg_pp0_iter36_resultf_3_reg_72;
        ap_phi_reg_pp0_iter39_resultf_3_reg_72 <= ap_phi_reg_pp0_iter38_resultf_3_reg_72;
        ap_phi_reg_pp0_iter3_expx_reg_58 <= ap_phi_reg_pp0_iter2_expx_reg_58;
        ap_phi_reg_pp0_iter3_resultf_3_reg_72 <= ap_phi_reg_pp0_iter2_resultf_3_reg_72;
        ap_phi_reg_pp0_iter40_resultf_3_reg_72 <= ap_phi_reg_pp0_iter39_resultf_3_reg_72;
        ap_phi_reg_pp0_iter4_expx_reg_58 <= ap_phi_reg_pp0_iter3_expx_reg_58;
        ap_phi_reg_pp0_iter4_resultf_3_reg_72 <= ap_phi_reg_pp0_iter3_resultf_3_reg_72;
        ap_phi_reg_pp0_iter5_expx_reg_58 <= ap_phi_reg_pp0_iter4_expx_reg_58;
        ap_phi_reg_pp0_iter5_resultf_3_reg_72 <= ap_phi_reg_pp0_iter4_resultf_3_reg_72;
        ap_phi_reg_pp0_iter6_resultf_3_reg_72 <= ap_phi_reg_pp0_iter5_resultf_3_reg_72;
        ap_phi_reg_pp0_iter7_expx_reg_58 <= ap_phi_reg_pp0_iter6_expx_reg_58;
        ap_phi_reg_pp0_iter7_resultf_3_reg_72 <= ap_phi_reg_pp0_iter6_resultf_3_reg_72;
        ap_phi_reg_pp0_iter8_expx_reg_58 <= ap_phi_reg_pp0_iter7_expx_reg_58;
        ap_phi_reg_pp0_iter9_expx_reg_58 <= ap_phi_reg_pp0_iter8_expx_reg_58;
        ap_phi_reg_pp0_iter9_resultf_3_reg_72 <= ap_phi_reg_pp0_iter8_resultf_3_reg_72;
        ap_predicate_pred44_state37 <= ((icmp_ln54_reg_443_pp0_iter34_reg == 1'd0) & (1'd1 == and_ln51_reg_439_pp0_iter34_reg) & (icmp_ln45_reg_416_pp0_iter34_reg == 1'd0) & (1'd0 == and_ln46_reg_425_pp0_iter34_reg) & (icmp_ln36_reg_412_pp0_iter34_reg == 1'd0));
        ap_predicate_pred53_state37 <= ((icmp_ln54_reg_443_pp0_iter34_reg == 1'd1) & (1'd1 == and_ln51_reg_439_pp0_iter34_reg) & (icmp_ln45_reg_416_pp0_iter34_reg == 1'd0) & (1'd0 == and_ln46_reg_425_pp0_iter34_reg) & (icmp_ln36_reg_412_pp0_iter34_reg == 1'd0));
        ap_predicate_pred614_state24 <= ((icmp_ln10_reg_469_pp0_iter21_reg == 1'd0) & (1'd1 == and_ln51_reg_439_pp0_iter21_reg) & (icmp_ln9_reg_465_pp0_iter21_reg == 1'd0) & (1'd0 == and_ln46_reg_425_pp0_iter21_reg) & (icmp_ln45_reg_416_pp0_iter21_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter21_reg == 1'd0));
        ap_predicate_pred731_state38 <= ((1'd1 == and_ln51_reg_439_pp0_iter35_reg) & (icmp_ln54_reg_443_pp0_iter35_reg == 1'd1) & (1'd0 == and_ln46_reg_425_pp0_iter35_reg) & (icmp_ln45_reg_416_pp0_iter35_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter35_reg == 1'd0));
        ap_predicate_pred744_state41 <= ((1'd1 == and_ln51_reg_439_pp0_iter38_reg) & (icmp_ln54_reg_443_pp0_iter38_reg == 1'd0) & (1'd0 == and_ln46_reg_425_pp0_iter38_reg) & (icmp_ln45_reg_416_pp0_iter38_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter38_reg == 1'd0));
        ap_predicate_pred800_state29 <= ((1'd1 == and_ln51_reg_439_pp0_iter26_reg) & (icmp_ln54_reg_443_pp0_iter26_reg == 1'd0) & (1'd0 == and_ln46_reg_425_pp0_iter26_reg) & (icmp_ln45_reg_416_pp0_iter26_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter26_reg == 1'd0));
        ap_predicate_pred805_state29 <= ((1'd1 == and_ln51_reg_439_pp0_iter26_reg) & (icmp_ln54_reg_443_pp0_iter26_reg == 1'd1) & (1'd0 == and_ln46_reg_425_pp0_iter26_reg) & (icmp_ln45_reg_416_pp0_iter26_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter26_reg == 1'd0));
        din_exp_reg_392 <= {{data_fu_158_p1[30:23]}};
        din_sign_reg_387 <= data_fu_158_p1[32'd31];
        din_sign_reg_387_pp0_iter10_reg <= din_sign_reg_387_pp0_iter9_reg;
        din_sign_reg_387_pp0_iter11_reg <= din_sign_reg_387_pp0_iter10_reg;
        din_sign_reg_387_pp0_iter12_reg <= din_sign_reg_387_pp0_iter11_reg;
        din_sign_reg_387_pp0_iter13_reg <= din_sign_reg_387_pp0_iter12_reg;
        din_sign_reg_387_pp0_iter14_reg <= din_sign_reg_387_pp0_iter13_reg;
        din_sign_reg_387_pp0_iter15_reg <= din_sign_reg_387_pp0_iter14_reg;
        din_sign_reg_387_pp0_iter16_reg <= din_sign_reg_387_pp0_iter15_reg;
        din_sign_reg_387_pp0_iter17_reg <= din_sign_reg_387_pp0_iter16_reg;
        din_sign_reg_387_pp0_iter18_reg <= din_sign_reg_387_pp0_iter17_reg;
        din_sign_reg_387_pp0_iter19_reg <= din_sign_reg_387_pp0_iter18_reg;
        din_sign_reg_387_pp0_iter1_reg <= din_sign_reg_387;
        din_sign_reg_387_pp0_iter20_reg <= din_sign_reg_387_pp0_iter19_reg;
        din_sign_reg_387_pp0_iter21_reg <= din_sign_reg_387_pp0_iter20_reg;
        din_sign_reg_387_pp0_iter22_reg <= din_sign_reg_387_pp0_iter21_reg;
        din_sign_reg_387_pp0_iter23_reg <= din_sign_reg_387_pp0_iter22_reg;
        din_sign_reg_387_pp0_iter24_reg <= din_sign_reg_387_pp0_iter23_reg;
        din_sign_reg_387_pp0_iter25_reg <= din_sign_reg_387_pp0_iter24_reg;
        din_sign_reg_387_pp0_iter26_reg <= din_sign_reg_387_pp0_iter25_reg;
        din_sign_reg_387_pp0_iter27_reg <= din_sign_reg_387_pp0_iter26_reg;
        din_sign_reg_387_pp0_iter28_reg <= din_sign_reg_387_pp0_iter27_reg;
        din_sign_reg_387_pp0_iter29_reg <= din_sign_reg_387_pp0_iter28_reg;
        din_sign_reg_387_pp0_iter2_reg <= din_sign_reg_387_pp0_iter1_reg;
        din_sign_reg_387_pp0_iter30_reg <= din_sign_reg_387_pp0_iter29_reg;
        din_sign_reg_387_pp0_iter31_reg <= din_sign_reg_387_pp0_iter30_reg;
        din_sign_reg_387_pp0_iter32_reg <= din_sign_reg_387_pp0_iter31_reg;
        din_sign_reg_387_pp0_iter33_reg <= din_sign_reg_387_pp0_iter32_reg;
        din_sign_reg_387_pp0_iter34_reg <= din_sign_reg_387_pp0_iter33_reg;
        din_sign_reg_387_pp0_iter35_reg <= din_sign_reg_387_pp0_iter34_reg;
        din_sign_reg_387_pp0_iter36_reg <= din_sign_reg_387_pp0_iter35_reg;
        din_sign_reg_387_pp0_iter37_reg <= din_sign_reg_387_pp0_iter36_reg;
        din_sign_reg_387_pp0_iter38_reg <= din_sign_reg_387_pp0_iter37_reg;
        din_sign_reg_387_pp0_iter39_reg <= din_sign_reg_387_pp0_iter38_reg;
        din_sign_reg_387_pp0_iter3_reg <= din_sign_reg_387_pp0_iter2_reg;
        din_sign_reg_387_pp0_iter40_reg <= din_sign_reg_387_pp0_iter39_reg;
        din_sign_reg_387_pp0_iter4_reg <= din_sign_reg_387_pp0_iter3_reg;
        din_sign_reg_387_pp0_iter5_reg <= din_sign_reg_387_pp0_iter4_reg;
        din_sign_reg_387_pp0_iter6_reg <= din_sign_reg_387_pp0_iter5_reg;
        din_sign_reg_387_pp0_iter7_reg <= din_sign_reg_387_pp0_iter6_reg;
        din_sign_reg_387_pp0_iter8_reg <= din_sign_reg_387_pp0_iter7_reg;
        din_sign_reg_387_pp0_iter9_reg <= din_sign_reg_387_pp0_iter8_reg;
        expx_reg_58_pp0_iter24_reg <= expx_reg_58;
        expx_reg_58_pp0_iter25_reg <= expx_reg_58_pp0_iter24_reg;
        expx_reg_58_pp0_iter26_reg <= expx_reg_58_pp0_iter25_reg;
        icmp_ln10_reg_469 <= icmp_ln10_fu_299_p2;
        icmp_ln10_reg_469_pp0_iter10_reg <= icmp_ln10_reg_469_pp0_iter9_reg;
        icmp_ln10_reg_469_pp0_iter11_reg <= icmp_ln10_reg_469_pp0_iter10_reg;
        icmp_ln10_reg_469_pp0_iter12_reg <= icmp_ln10_reg_469_pp0_iter11_reg;
        icmp_ln10_reg_469_pp0_iter13_reg <= icmp_ln10_reg_469_pp0_iter12_reg;
        icmp_ln10_reg_469_pp0_iter14_reg <= icmp_ln10_reg_469_pp0_iter13_reg;
        icmp_ln10_reg_469_pp0_iter15_reg <= icmp_ln10_reg_469_pp0_iter14_reg;
        icmp_ln10_reg_469_pp0_iter16_reg <= icmp_ln10_reg_469_pp0_iter15_reg;
        icmp_ln10_reg_469_pp0_iter17_reg <= icmp_ln10_reg_469_pp0_iter16_reg;
        icmp_ln10_reg_469_pp0_iter18_reg <= icmp_ln10_reg_469_pp0_iter17_reg;
        icmp_ln10_reg_469_pp0_iter19_reg <= icmp_ln10_reg_469_pp0_iter18_reg;
        icmp_ln10_reg_469_pp0_iter20_reg <= icmp_ln10_reg_469_pp0_iter19_reg;
        icmp_ln10_reg_469_pp0_iter21_reg <= icmp_ln10_reg_469_pp0_iter20_reg;
        icmp_ln10_reg_469_pp0_iter6_reg <= icmp_ln10_reg_469;
        icmp_ln10_reg_469_pp0_iter7_reg <= icmp_ln10_reg_469_pp0_iter6_reg;
        icmp_ln10_reg_469_pp0_iter8_reg <= icmp_ln10_reg_469_pp0_iter7_reg;
        icmp_ln10_reg_469_pp0_iter9_reg <= icmp_ln10_reg_469_pp0_iter8_reg;
        icmp_ln36_reg_412 <= icmp_ln36_fu_196_p2;
        icmp_ln36_reg_412_pp0_iter10_reg <= icmp_ln36_reg_412_pp0_iter9_reg;
        icmp_ln36_reg_412_pp0_iter11_reg <= icmp_ln36_reg_412_pp0_iter10_reg;
        icmp_ln36_reg_412_pp0_iter12_reg <= icmp_ln36_reg_412_pp0_iter11_reg;
        icmp_ln36_reg_412_pp0_iter13_reg <= icmp_ln36_reg_412_pp0_iter12_reg;
        icmp_ln36_reg_412_pp0_iter14_reg <= icmp_ln36_reg_412_pp0_iter13_reg;
        icmp_ln36_reg_412_pp0_iter15_reg <= icmp_ln36_reg_412_pp0_iter14_reg;
        icmp_ln36_reg_412_pp0_iter16_reg <= icmp_ln36_reg_412_pp0_iter15_reg;
        icmp_ln36_reg_412_pp0_iter17_reg <= icmp_ln36_reg_412_pp0_iter16_reg;
        icmp_ln36_reg_412_pp0_iter18_reg <= icmp_ln36_reg_412_pp0_iter17_reg;
        icmp_ln36_reg_412_pp0_iter19_reg <= icmp_ln36_reg_412_pp0_iter18_reg;
        icmp_ln36_reg_412_pp0_iter1_reg <= icmp_ln36_reg_412;
        icmp_ln36_reg_412_pp0_iter20_reg <= icmp_ln36_reg_412_pp0_iter19_reg;
        icmp_ln36_reg_412_pp0_iter21_reg <= icmp_ln36_reg_412_pp0_iter20_reg;
        icmp_ln36_reg_412_pp0_iter22_reg <= icmp_ln36_reg_412_pp0_iter21_reg;
        icmp_ln36_reg_412_pp0_iter23_reg <= icmp_ln36_reg_412_pp0_iter22_reg;
        icmp_ln36_reg_412_pp0_iter24_reg <= icmp_ln36_reg_412_pp0_iter23_reg;
        icmp_ln36_reg_412_pp0_iter25_reg <= icmp_ln36_reg_412_pp0_iter24_reg;
        icmp_ln36_reg_412_pp0_iter26_reg <= icmp_ln36_reg_412_pp0_iter25_reg;
        icmp_ln36_reg_412_pp0_iter27_reg <= icmp_ln36_reg_412_pp0_iter26_reg;
        icmp_ln36_reg_412_pp0_iter28_reg <= icmp_ln36_reg_412_pp0_iter27_reg;
        icmp_ln36_reg_412_pp0_iter29_reg <= icmp_ln36_reg_412_pp0_iter28_reg;
        icmp_ln36_reg_412_pp0_iter2_reg <= icmp_ln36_reg_412_pp0_iter1_reg;
        icmp_ln36_reg_412_pp0_iter30_reg <= icmp_ln36_reg_412_pp0_iter29_reg;
        icmp_ln36_reg_412_pp0_iter31_reg <= icmp_ln36_reg_412_pp0_iter30_reg;
        icmp_ln36_reg_412_pp0_iter32_reg <= icmp_ln36_reg_412_pp0_iter31_reg;
        icmp_ln36_reg_412_pp0_iter33_reg <= icmp_ln36_reg_412_pp0_iter32_reg;
        icmp_ln36_reg_412_pp0_iter34_reg <= icmp_ln36_reg_412_pp0_iter33_reg;
        icmp_ln36_reg_412_pp0_iter35_reg <= icmp_ln36_reg_412_pp0_iter34_reg;
        icmp_ln36_reg_412_pp0_iter36_reg <= icmp_ln36_reg_412_pp0_iter35_reg;
        icmp_ln36_reg_412_pp0_iter37_reg <= icmp_ln36_reg_412_pp0_iter36_reg;
        icmp_ln36_reg_412_pp0_iter38_reg <= icmp_ln36_reg_412_pp0_iter37_reg;
        icmp_ln36_reg_412_pp0_iter39_reg <= icmp_ln36_reg_412_pp0_iter38_reg;
        icmp_ln36_reg_412_pp0_iter3_reg <= icmp_ln36_reg_412_pp0_iter2_reg;
        icmp_ln36_reg_412_pp0_iter4_reg <= icmp_ln36_reg_412_pp0_iter3_reg;
        icmp_ln36_reg_412_pp0_iter5_reg <= icmp_ln36_reg_412_pp0_iter4_reg;
        icmp_ln36_reg_412_pp0_iter6_reg <= icmp_ln36_reg_412_pp0_iter5_reg;
        icmp_ln36_reg_412_pp0_iter7_reg <= icmp_ln36_reg_412_pp0_iter6_reg;
        icmp_ln36_reg_412_pp0_iter8_reg <= icmp_ln36_reg_412_pp0_iter7_reg;
        icmp_ln36_reg_412_pp0_iter9_reg <= icmp_ln36_reg_412_pp0_iter8_reg;
        icmp_ln38_reg_434 <= icmp_ln38_fu_242_p2;
        icmp_ln38_reg_434_pp0_iter10_reg <= icmp_ln38_reg_434_pp0_iter9_reg;
        icmp_ln38_reg_434_pp0_iter11_reg <= icmp_ln38_reg_434_pp0_iter10_reg;
        icmp_ln38_reg_434_pp0_iter12_reg <= icmp_ln38_reg_434_pp0_iter11_reg;
        icmp_ln38_reg_434_pp0_iter13_reg <= icmp_ln38_reg_434_pp0_iter12_reg;
        icmp_ln38_reg_434_pp0_iter14_reg <= icmp_ln38_reg_434_pp0_iter13_reg;
        icmp_ln38_reg_434_pp0_iter15_reg <= icmp_ln38_reg_434_pp0_iter14_reg;
        icmp_ln38_reg_434_pp0_iter16_reg <= icmp_ln38_reg_434_pp0_iter15_reg;
        icmp_ln38_reg_434_pp0_iter17_reg <= icmp_ln38_reg_434_pp0_iter16_reg;
        icmp_ln38_reg_434_pp0_iter18_reg <= icmp_ln38_reg_434_pp0_iter17_reg;
        icmp_ln38_reg_434_pp0_iter19_reg <= icmp_ln38_reg_434_pp0_iter18_reg;
        icmp_ln38_reg_434_pp0_iter1_reg <= icmp_ln38_reg_434;
        icmp_ln38_reg_434_pp0_iter20_reg <= icmp_ln38_reg_434_pp0_iter19_reg;
        icmp_ln38_reg_434_pp0_iter21_reg <= icmp_ln38_reg_434_pp0_iter20_reg;
        icmp_ln38_reg_434_pp0_iter22_reg <= icmp_ln38_reg_434_pp0_iter21_reg;
        icmp_ln38_reg_434_pp0_iter23_reg <= icmp_ln38_reg_434_pp0_iter22_reg;
        icmp_ln38_reg_434_pp0_iter24_reg <= icmp_ln38_reg_434_pp0_iter23_reg;
        icmp_ln38_reg_434_pp0_iter25_reg <= icmp_ln38_reg_434_pp0_iter24_reg;
        icmp_ln38_reg_434_pp0_iter26_reg <= icmp_ln38_reg_434_pp0_iter25_reg;
        icmp_ln38_reg_434_pp0_iter27_reg <= icmp_ln38_reg_434_pp0_iter26_reg;
        icmp_ln38_reg_434_pp0_iter28_reg <= icmp_ln38_reg_434_pp0_iter27_reg;
        icmp_ln38_reg_434_pp0_iter29_reg <= icmp_ln38_reg_434_pp0_iter28_reg;
        icmp_ln38_reg_434_pp0_iter2_reg <= icmp_ln38_reg_434_pp0_iter1_reg;
        icmp_ln38_reg_434_pp0_iter30_reg <= icmp_ln38_reg_434_pp0_iter29_reg;
        icmp_ln38_reg_434_pp0_iter31_reg <= icmp_ln38_reg_434_pp0_iter30_reg;
        icmp_ln38_reg_434_pp0_iter32_reg <= icmp_ln38_reg_434_pp0_iter31_reg;
        icmp_ln38_reg_434_pp0_iter33_reg <= icmp_ln38_reg_434_pp0_iter32_reg;
        icmp_ln38_reg_434_pp0_iter34_reg <= icmp_ln38_reg_434_pp0_iter33_reg;
        icmp_ln38_reg_434_pp0_iter35_reg <= icmp_ln38_reg_434_pp0_iter34_reg;
        icmp_ln38_reg_434_pp0_iter36_reg <= icmp_ln38_reg_434_pp0_iter35_reg;
        icmp_ln38_reg_434_pp0_iter37_reg <= icmp_ln38_reg_434_pp0_iter36_reg;
        icmp_ln38_reg_434_pp0_iter38_reg <= icmp_ln38_reg_434_pp0_iter37_reg;
        icmp_ln38_reg_434_pp0_iter39_reg <= icmp_ln38_reg_434_pp0_iter38_reg;
        icmp_ln38_reg_434_pp0_iter3_reg <= icmp_ln38_reg_434_pp0_iter2_reg;
        icmp_ln38_reg_434_pp0_iter4_reg <= icmp_ln38_reg_434_pp0_iter3_reg;
        icmp_ln38_reg_434_pp0_iter5_reg <= icmp_ln38_reg_434_pp0_iter4_reg;
        icmp_ln38_reg_434_pp0_iter6_reg <= icmp_ln38_reg_434_pp0_iter5_reg;
        icmp_ln38_reg_434_pp0_iter7_reg <= icmp_ln38_reg_434_pp0_iter6_reg;
        icmp_ln38_reg_434_pp0_iter8_reg <= icmp_ln38_reg_434_pp0_iter7_reg;
        icmp_ln38_reg_434_pp0_iter9_reg <= icmp_ln38_reg_434_pp0_iter8_reg;
        icmp_ln45_reg_416 <= icmp_ln45_fu_202_p2;
        icmp_ln45_reg_416_pp0_iter10_reg <= icmp_ln45_reg_416_pp0_iter9_reg;
        icmp_ln45_reg_416_pp0_iter11_reg <= icmp_ln45_reg_416_pp0_iter10_reg;
        icmp_ln45_reg_416_pp0_iter12_reg <= icmp_ln45_reg_416_pp0_iter11_reg;
        icmp_ln45_reg_416_pp0_iter13_reg <= icmp_ln45_reg_416_pp0_iter12_reg;
        icmp_ln45_reg_416_pp0_iter14_reg <= icmp_ln45_reg_416_pp0_iter13_reg;
        icmp_ln45_reg_416_pp0_iter15_reg <= icmp_ln45_reg_416_pp0_iter14_reg;
        icmp_ln45_reg_416_pp0_iter16_reg <= icmp_ln45_reg_416_pp0_iter15_reg;
        icmp_ln45_reg_416_pp0_iter17_reg <= icmp_ln45_reg_416_pp0_iter16_reg;
        icmp_ln45_reg_416_pp0_iter18_reg <= icmp_ln45_reg_416_pp0_iter17_reg;
        icmp_ln45_reg_416_pp0_iter19_reg <= icmp_ln45_reg_416_pp0_iter18_reg;
        icmp_ln45_reg_416_pp0_iter1_reg <= icmp_ln45_reg_416;
        icmp_ln45_reg_416_pp0_iter20_reg <= icmp_ln45_reg_416_pp0_iter19_reg;
        icmp_ln45_reg_416_pp0_iter21_reg <= icmp_ln45_reg_416_pp0_iter20_reg;
        icmp_ln45_reg_416_pp0_iter22_reg <= icmp_ln45_reg_416_pp0_iter21_reg;
        icmp_ln45_reg_416_pp0_iter23_reg <= icmp_ln45_reg_416_pp0_iter22_reg;
        icmp_ln45_reg_416_pp0_iter24_reg <= icmp_ln45_reg_416_pp0_iter23_reg;
        icmp_ln45_reg_416_pp0_iter25_reg <= icmp_ln45_reg_416_pp0_iter24_reg;
        icmp_ln45_reg_416_pp0_iter26_reg <= icmp_ln45_reg_416_pp0_iter25_reg;
        icmp_ln45_reg_416_pp0_iter27_reg <= icmp_ln45_reg_416_pp0_iter26_reg;
        icmp_ln45_reg_416_pp0_iter28_reg <= icmp_ln45_reg_416_pp0_iter27_reg;
        icmp_ln45_reg_416_pp0_iter29_reg <= icmp_ln45_reg_416_pp0_iter28_reg;
        icmp_ln45_reg_416_pp0_iter2_reg <= icmp_ln45_reg_416_pp0_iter1_reg;
        icmp_ln45_reg_416_pp0_iter30_reg <= icmp_ln45_reg_416_pp0_iter29_reg;
        icmp_ln45_reg_416_pp0_iter31_reg <= icmp_ln45_reg_416_pp0_iter30_reg;
        icmp_ln45_reg_416_pp0_iter32_reg <= icmp_ln45_reg_416_pp0_iter31_reg;
        icmp_ln45_reg_416_pp0_iter33_reg <= icmp_ln45_reg_416_pp0_iter32_reg;
        icmp_ln45_reg_416_pp0_iter34_reg <= icmp_ln45_reg_416_pp0_iter33_reg;
        icmp_ln45_reg_416_pp0_iter35_reg <= icmp_ln45_reg_416_pp0_iter34_reg;
        icmp_ln45_reg_416_pp0_iter36_reg <= icmp_ln45_reg_416_pp0_iter35_reg;
        icmp_ln45_reg_416_pp0_iter37_reg <= icmp_ln45_reg_416_pp0_iter36_reg;
        icmp_ln45_reg_416_pp0_iter38_reg <= icmp_ln45_reg_416_pp0_iter37_reg;
        icmp_ln45_reg_416_pp0_iter3_reg <= icmp_ln45_reg_416_pp0_iter2_reg;
        icmp_ln45_reg_416_pp0_iter4_reg <= icmp_ln45_reg_416_pp0_iter3_reg;
        icmp_ln45_reg_416_pp0_iter5_reg <= icmp_ln45_reg_416_pp0_iter4_reg;
        icmp_ln45_reg_416_pp0_iter6_reg <= icmp_ln45_reg_416_pp0_iter5_reg;
        icmp_ln45_reg_416_pp0_iter7_reg <= icmp_ln45_reg_416_pp0_iter6_reg;
        icmp_ln45_reg_416_pp0_iter8_reg <= icmp_ln45_reg_416_pp0_iter7_reg;
        icmp_ln45_reg_416_pp0_iter9_reg <= icmp_ln45_reg_416_pp0_iter8_reg;
        icmp_ln46_1_reg_420 <= icmp_ln46_1_fu_214_p2;
        icmp_ln51_reg_429 <= icmp_ln51_fu_236_p2;
        icmp_ln54_reg_443 <= icmp_ln54_fu_258_p2;
        icmp_ln54_reg_443_pp0_iter10_reg <= icmp_ln54_reg_443_pp0_iter9_reg;
        icmp_ln54_reg_443_pp0_iter11_reg <= icmp_ln54_reg_443_pp0_iter10_reg;
        icmp_ln54_reg_443_pp0_iter12_reg <= icmp_ln54_reg_443_pp0_iter11_reg;
        icmp_ln54_reg_443_pp0_iter13_reg <= icmp_ln54_reg_443_pp0_iter12_reg;
        icmp_ln54_reg_443_pp0_iter14_reg <= icmp_ln54_reg_443_pp0_iter13_reg;
        icmp_ln54_reg_443_pp0_iter15_reg <= icmp_ln54_reg_443_pp0_iter14_reg;
        icmp_ln54_reg_443_pp0_iter16_reg <= icmp_ln54_reg_443_pp0_iter15_reg;
        icmp_ln54_reg_443_pp0_iter17_reg <= icmp_ln54_reg_443_pp0_iter16_reg;
        icmp_ln54_reg_443_pp0_iter18_reg <= icmp_ln54_reg_443_pp0_iter17_reg;
        icmp_ln54_reg_443_pp0_iter19_reg <= icmp_ln54_reg_443_pp0_iter18_reg;
        icmp_ln54_reg_443_pp0_iter20_reg <= icmp_ln54_reg_443_pp0_iter19_reg;
        icmp_ln54_reg_443_pp0_iter21_reg <= icmp_ln54_reg_443_pp0_iter20_reg;
        icmp_ln54_reg_443_pp0_iter22_reg <= icmp_ln54_reg_443_pp0_iter21_reg;
        icmp_ln54_reg_443_pp0_iter23_reg <= icmp_ln54_reg_443_pp0_iter22_reg;
        icmp_ln54_reg_443_pp0_iter24_reg <= icmp_ln54_reg_443_pp0_iter23_reg;
        icmp_ln54_reg_443_pp0_iter25_reg <= icmp_ln54_reg_443_pp0_iter24_reg;
        icmp_ln54_reg_443_pp0_iter26_reg <= icmp_ln54_reg_443_pp0_iter25_reg;
        icmp_ln54_reg_443_pp0_iter27_reg <= icmp_ln54_reg_443_pp0_iter26_reg;
        icmp_ln54_reg_443_pp0_iter28_reg <= icmp_ln54_reg_443_pp0_iter27_reg;
        icmp_ln54_reg_443_pp0_iter29_reg <= icmp_ln54_reg_443_pp0_iter28_reg;
        icmp_ln54_reg_443_pp0_iter2_reg <= icmp_ln54_reg_443;
        icmp_ln54_reg_443_pp0_iter30_reg <= icmp_ln54_reg_443_pp0_iter29_reg;
        icmp_ln54_reg_443_pp0_iter31_reg <= icmp_ln54_reg_443_pp0_iter30_reg;
        icmp_ln54_reg_443_pp0_iter32_reg <= icmp_ln54_reg_443_pp0_iter31_reg;
        icmp_ln54_reg_443_pp0_iter33_reg <= icmp_ln54_reg_443_pp0_iter32_reg;
        icmp_ln54_reg_443_pp0_iter34_reg <= icmp_ln54_reg_443_pp0_iter33_reg;
        icmp_ln54_reg_443_pp0_iter35_reg <= icmp_ln54_reg_443_pp0_iter34_reg;
        icmp_ln54_reg_443_pp0_iter36_reg <= icmp_ln54_reg_443_pp0_iter35_reg;
        icmp_ln54_reg_443_pp0_iter37_reg <= icmp_ln54_reg_443_pp0_iter36_reg;
        icmp_ln54_reg_443_pp0_iter38_reg <= icmp_ln54_reg_443_pp0_iter37_reg;
        icmp_ln54_reg_443_pp0_iter3_reg <= icmp_ln54_reg_443_pp0_iter2_reg;
        icmp_ln54_reg_443_pp0_iter4_reg <= icmp_ln54_reg_443_pp0_iter3_reg;
        icmp_ln54_reg_443_pp0_iter5_reg <= icmp_ln54_reg_443_pp0_iter4_reg;
        icmp_ln54_reg_443_pp0_iter6_reg <= icmp_ln54_reg_443_pp0_iter5_reg;
        icmp_ln54_reg_443_pp0_iter7_reg <= icmp_ln54_reg_443_pp0_iter6_reg;
        icmp_ln54_reg_443_pp0_iter8_reg <= icmp_ln54_reg_443_pp0_iter7_reg;
        icmp_ln54_reg_443_pp0_iter9_reg <= icmp_ln54_reg_443_pp0_iter8_reg;
        icmp_ln9_reg_465 <= icmp_ln9_fu_293_p2;
        icmp_ln9_reg_465_pp0_iter10_reg <= icmp_ln9_reg_465_pp0_iter9_reg;
        icmp_ln9_reg_465_pp0_iter11_reg <= icmp_ln9_reg_465_pp0_iter10_reg;
        icmp_ln9_reg_465_pp0_iter12_reg <= icmp_ln9_reg_465_pp0_iter11_reg;
        icmp_ln9_reg_465_pp0_iter13_reg <= icmp_ln9_reg_465_pp0_iter12_reg;
        icmp_ln9_reg_465_pp0_iter14_reg <= icmp_ln9_reg_465_pp0_iter13_reg;
        icmp_ln9_reg_465_pp0_iter15_reg <= icmp_ln9_reg_465_pp0_iter14_reg;
        icmp_ln9_reg_465_pp0_iter16_reg <= icmp_ln9_reg_465_pp0_iter15_reg;
        icmp_ln9_reg_465_pp0_iter17_reg <= icmp_ln9_reg_465_pp0_iter16_reg;
        icmp_ln9_reg_465_pp0_iter18_reg <= icmp_ln9_reg_465_pp0_iter17_reg;
        icmp_ln9_reg_465_pp0_iter19_reg <= icmp_ln9_reg_465_pp0_iter18_reg;
        icmp_ln9_reg_465_pp0_iter20_reg <= icmp_ln9_reg_465_pp0_iter19_reg;
        icmp_ln9_reg_465_pp0_iter21_reg <= icmp_ln9_reg_465_pp0_iter20_reg;
        icmp_ln9_reg_465_pp0_iter6_reg <= icmp_ln9_reg_465;
        icmp_ln9_reg_465_pp0_iter7_reg <= icmp_ln9_reg_465_pp0_iter6_reg;
        icmp_ln9_reg_465_pp0_iter8_reg <= icmp_ln9_reg_465_pp0_iter7_reg;
        icmp_ln9_reg_465_pp0_iter9_reg <= icmp_ln9_reg_465_pp0_iter8_reg;
        resultf_reg_478 <= grp_fu_126_p2;
        sub_i_reg_488 <= grp_fu_147_p2;
        t_reg_397 <= t_fu_182_p1;
        trunc_ln66_reg_503 <= trunc_ln66_fu_323_p1;
        x_3_reg_458 <= x_3_fu_275_p3;
        xd_reg_473 <= grp_fu_139_p1;
        xor_ln66_reg_498 <= xor_ln66_fu_317_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_pred53_state37 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_pred44_state37 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_152 <= grp_fu_130_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp108)) begin
        tmp_5_reg_483 <= grp_exp_generic_double_s_fu_90_ap_return;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp98)) begin
        grp_exp_generic_double_s_fu_90_ap_ce = 1'b1;
    end else begin
        grp_exp_generic_double_s_fu_90_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_pred805_state29 == 1'b1)) begin
            grp_fu_130_p0 = bitcast_ln66_1_fu_333_p1;
        end else if ((ap_predicate_pred800_state29 == 1'b1)) begin
            grp_fu_130_p0 = 32'd1073741824;
        end else begin
            grp_fu_130_p0 = 'bx;
        end
    end else begin
        grp_fu_130_p0 = 'bx;
    end
end

assign abst_in_fu_190_p1 = zext_ln313_fu_186_p1;

assign and_ln46_fu_220_p2 = (icmp_ln46_fu_208_p2 & icmp_ln46_1_fu_214_p2);

assign and_ln51_fu_252_p2 = (or_ln51_fu_248_p2 & grp_fu_142_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp108 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp98 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp98 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_668 = ((1'd1 == and_ln51_reg_439_pp0_iter4_reg) & (icmp_ln9_fu_293_p2 == 1'd1) & (1'd0 == and_ln46_reg_425_pp0_iter4_reg) & (icmp_ln45_reg_416_pp0_iter4_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_condition_673 = ((icmp_ln10_fu_299_p2 == 1'd1) & (1'd1 == and_ln51_reg_439_pp0_iter4_reg) & (icmp_ln9_fu_293_p2 == 1'd0) & (1'd0 == and_ln46_reg_425_pp0_iter4_reg) & (icmp_ln45_reg_416_pp0_iter4_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_condition_721 = (((icmp_ln45_reg_416_pp0_iter6_reg == 1'd1) & (icmp_ln36_reg_412_pp0_iter6_reg == 1'd0)) | ((1'd1 == and_ln46_reg_425_pp0_iter6_reg) & (icmp_ln36_reg_412_pp0_iter6_reg == 1'd0)));
end

always @ (*) begin
    ap_condition_767 = ((icmp_ln45_reg_416 == 1'd0) & (1'd0 == and_ln46_reg_425) & (1'd0 == and_ln51_fu_252_p2) & (icmp_ln36_reg_412 == 1'd0));
end

assign ap_phi_reg_pp0_iter0_expx_reg_58 = 'bx;

assign ap_phi_reg_pp0_iter0_resultf_3_reg_72 = 'bx;

always @ (*) begin
    ap_predicate_op98_call_state8 = ((icmp_ln10_reg_469_pp0_iter6_reg == 1'd0) & (1'd1 == and_ln51_reg_439_pp0_iter6_reg) & (icmp_ln9_reg_465_pp0_iter6_reg == 1'd0) & (1'd0 == and_ln46_reg_425_pp0_iter6_reg) & (icmp_ln45_reg_416_pp0_iter6_reg == 1'd0) & (icmp_ln36_reg_412_pp0_iter6_reg == 1'd0));
end

assign ap_return = ((din_sign_reg_387_pp0_iter40_reg[0:0] == 1'b1) ? bitcast_ln83_1_fu_376_p1 : resultf_3_reg_72);

assign bit_sel1_fu_350_p3 = bitcast_ln83_fu_346_p1[32'd31];

assign bit_sel_fu_309_p3 = bitcast_ln66_fu_305_p1[32'd31];

assign bitcast_ln66_1_fu_333_p1 = xor_ln_fu_327_p3;

assign bitcast_ln66_fu_305_p1 = expx_reg_58_pp0_iter26_reg;

assign bitcast_ln83_1_fu_376_p1 = xor_ln1_fu_368_p3;

assign bitcast_ln83_fu_346_p1 = resultf_3_reg_72;

assign data_1_fu_282_p1 = x_3_reg_458;

assign data_fu_158_p1 = t_in_int_reg;

assign din_exp_fu_170_p3 = {{data_fu_158_p1[30:23]}};

assign din_sig_fu_178_p1 = data_fu_158_p1[22:0];

assign grp_fu_106_p0 = or_ln_fu_263_p3;

assign icmp_ln10_fu_299_p2 = ((xs_exp_1_fu_285_p3 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_196_p2 = ((din_exp_fu_170_p3 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_242_p2 = ((din_sig_fu_178_p1 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_202_p2 = ((din_exp_fu_170_p3 < 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_214_p2 = ((din_sig_fu_178_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_208_p2 = ((din_exp_fu_170_p3 == 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_236_p2 = ((tmp_fu_226_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_258_p2 = ((din_exp_reg_392 < 8'd127) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_293_p2 = ((xs_exp_1_fu_285_p3 == 8'd0) ? 1'b1 : 1'b0);

assign or_ln51_fu_248_p2 = (icmp_ln51_reg_429 | icmp_ln46_1_reg_420);

assign or_ln_fu_263_p3 = {{1'd1}, {t_reg_397}};

assign select_ln38_fu_338_p3 = ((icmp_ln38_reg_434_pp0_iter39_reg[0:0] == 1'b1) ? 32'd2147483647 : 32'd1065353216);

assign t_fu_182_p1 = data_fu_158_p1[30:0];

assign tmp_fu_226_p4 = {{data_fu_158_p1[30:23]}};

assign trunc_ln66_fu_323_p1 = bitcast_ln66_fu_305_p1[30:0];

assign trunc_ln83_fu_364_p1 = bitcast_ln83_fu_346_p1[30:0];

assign x_3_fu_275_p3 = ((icmp_ln54_reg_443_pp0_iter3_reg[0:0] == 1'b1) ? grp_fu_106_p2 : grp_fu_110_p2);

assign xor_ln1_fu_368_p3 = {{xor_ln83_fu_358_p2}, {trunc_ln83_fu_364_p1}};

assign xor_ln66_fu_317_p2 = (bit_sel_fu_309_p3 ^ 1'd1);

assign xor_ln83_fu_358_p2 = (bit_sel1_fu_350_p3 ^ 1'd1);

assign xor_ln_fu_327_p3 = {{xor_ln66_reg_498}, {trunc_ln66_reg_503}};

assign xs_exp_1_fu_285_p3 = {{data_1_fu_282_p1[30:23]}};

assign zext_ln313_fu_186_p1 = t_fu_182_p1;

always @ (posedge ap_clk) begin
    abst_in_reg_402[31] <= 1'b0;
    abst_in_reg_402_pp0_iter1_reg[31] <= 1'b0;
    abst_in_reg_402_pp0_iter2_reg[31] <= 1'b0;
    abst_in_reg_402_pp0_iter3_reg[31] <= 1'b0;
end

endmodule //forward_generic_tanh_float_s
