-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (win64) Build 6140274 Thu May 22 00:12:29 MDT 2025
-- Date        : Mon Nov 10 11:28:24 2025
-- Host        : DJJ running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/design_1_forward_0_25_stub.vhdl
-- Design      : design_1_forward_0_25
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu3eg-sbva484-2-i
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_forward_0_25 is
  Port ( 
    s_axi_CTRL_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_CTRL_ARREADY : out STD_LOGIC;
    s_axi_CTRL_ARVALID : in STD_LOGIC;
    s_axi_CTRL_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_CTRL_AWREADY : out STD_LOGIC;
    s_axi_CTRL_AWVALID : in STD_LOGIC;
    s_axi_CTRL_BREADY : in STD_LOGIC;
    s_axi_CTRL_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_CTRL_BVALID : out STD_LOGIC;
    s_axi_CTRL_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_CTRL_RREADY : in STD_LOGIC;
    s_axi_CTRL_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_CTRL_RVALID : out STD_LOGIC;
    s_axi_CTRL_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_CTRL_WREADY : out STD_LOGIC;
    s_axi_CTRL_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_CTRL_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_INPUT_r_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_INPUT_r_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_INPUT_r_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_INPUT_r_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_INPUT_r_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_INPUT_r_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_INPUT_r_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_INPUT_r_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_INPUT_r_ARREADY : in STD_LOGIC;
    m_axi_INPUT_r_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_INPUT_r_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_INPUT_r_ARVALID : out STD_LOGIC;
    m_axi_INPUT_r_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_INPUT_r_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_INPUT_r_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_INPUT_r_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_INPUT_r_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_INPUT_r_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_INPUT_r_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_INPUT_r_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_INPUT_r_AWREADY : in STD_LOGIC;
    m_axi_INPUT_r_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_INPUT_r_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_INPUT_r_AWVALID : out STD_LOGIC;
    m_axi_INPUT_r_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_INPUT_r_BREADY : out STD_LOGIC;
    m_axi_INPUT_r_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_INPUT_r_BVALID : in STD_LOGIC;
    m_axi_INPUT_r_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_INPUT_r_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_INPUT_r_RLAST : in STD_LOGIC;
    m_axi_INPUT_r_RREADY : out STD_LOGIC;
    m_axi_INPUT_r_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_INPUT_r_RVALID : in STD_LOGIC;
    m_axi_INPUT_r_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_INPUT_r_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_INPUT_r_WLAST : out STD_LOGIC;
    m_axi_INPUT_r_WREADY : in STD_LOGIC;
    m_axi_INPUT_r_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_INPUT_r_WVALID : out STD_LOGIC;
    m_axi_OUTPUT_r_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_OUTPUT_r_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_OUTPUT_r_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_OUTPUT_r_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_OUTPUT_r_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_OUTPUT_r_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_OUTPUT_r_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_OUTPUT_r_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_OUTPUT_r_ARREADY : in STD_LOGIC;
    m_axi_OUTPUT_r_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_OUTPUT_r_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_OUTPUT_r_ARVALID : out STD_LOGIC;
    m_axi_OUTPUT_r_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_OUTPUT_r_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_OUTPUT_r_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_OUTPUT_r_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_OUTPUT_r_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_OUTPUT_r_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_OUTPUT_r_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_OUTPUT_r_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_OUTPUT_r_AWREADY : in STD_LOGIC;
    m_axi_OUTPUT_r_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_OUTPUT_r_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_OUTPUT_r_AWVALID : out STD_LOGIC;
    m_axi_OUTPUT_r_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_OUTPUT_r_BREADY : out STD_LOGIC;
    m_axi_OUTPUT_r_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_OUTPUT_r_BVALID : in STD_LOGIC;
    m_axi_OUTPUT_r_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_OUTPUT_r_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_OUTPUT_r_RLAST : in STD_LOGIC;
    m_axi_OUTPUT_r_RREADY : out STD_LOGIC;
    m_axi_OUTPUT_r_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_OUTPUT_r_RVALID : in STD_LOGIC;
    m_axi_OUTPUT_r_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_OUTPUT_r_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_OUTPUT_r_WLAST : out STD_LOGIC;
    m_axi_OUTPUT_r_WREADY : in STD_LOGIC;
    m_axi_OUTPUT_r_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_OUTPUT_r_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_1_forward_0_25 : entity is "design_1_forward_0_25,forward,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of design_1_forward_0_25 : entity is "design_1_forward_0_25,forward,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=forward,x_ipVersion=1.0,x_ipCoreRevision=2114342000,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CTRL_ADDR_WIDTH=6,C_S_AXI_CTRL_DATA_WIDTH=32,C_M_AXI_INPUT_R_ID_WIDTH=1,C_M_AXI_INPUT_R_ADDR_WIDTH=64,C_M_AXI_INPUT_R_DATA_WIDTH=32,C_M_AXI_INPUT_R_AWUSER_WIDTH=1,C_M_AXI_INPUT_R_ARUSER_WIDTH=1,C_M_AXI_INPUT_R_WUSER_WIDTH=1,C_M_AXI_INPUT_R_RUSER_WIDTH=1,C_M_AXI_INPUT_R_BUSER_WIDTH=1,C_M_AXI_INPUT_R_USER_VALUE=0x00000000,C_M_AXI_INPUT_R_PROT_VALUE=000,C_M_AXI_INPUT_R_CACHE_VALUE=0011,C_M_AXI_OUTPUT_R_ID_WIDTH=1,C_M_AXI_OUTPUT_R_ADDR_WIDTH=64,C_M_AXI_OUTPUT_R_DATA_WIDTH=32,C_M_AXI_OUTPUT_R_AWUSER_WIDTH=1,C_M_AXI_OUTPUT_R_ARUSER_WIDTH=1,C_M_AXI_OUTPUT_R_WUSER_WIDTH=1,C_M_AXI_OUTPUT_R_RUSER_WIDTH=1,C_M_AXI_OUTPUT_R_BUSER_WIDTH=1,C_M_AXI_OUTPUT_R_USER_VALUE=0x00000000,C_M_AXI_OUTPUT_R_PROT_VALUE=000,C_M_AXI_OUTPUT_R_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_1_forward_0_25 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of design_1_forward_0_25 : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of design_1_forward_0_25 : entity is "yes";
end design_1_forward_0_25;

architecture stub of design_1_forward_0_25 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_CTRL_ARADDR[5:0],s_axi_CTRL_ARREADY,s_axi_CTRL_ARVALID,s_axi_CTRL_AWADDR[5:0],s_axi_CTRL_AWREADY,s_axi_CTRL_AWVALID,s_axi_CTRL_BREADY,s_axi_CTRL_BRESP[1:0],s_axi_CTRL_BVALID,s_axi_CTRL_RDATA[31:0],s_axi_CTRL_RREADY,s_axi_CTRL_RRESP[1:0],s_axi_CTRL_RVALID,s_axi_CTRL_WDATA[31:0],s_axi_CTRL_WREADY,s_axi_CTRL_WSTRB[3:0],s_axi_CTRL_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_INPUT_r_ARADDR[63:0],m_axi_INPUT_r_ARBURST[1:0],m_axi_INPUT_r_ARCACHE[3:0],m_axi_INPUT_r_ARID[0:0],m_axi_INPUT_r_ARLEN[7:0],m_axi_INPUT_r_ARLOCK[1:0],m_axi_INPUT_r_ARPROT[2:0],m_axi_INPUT_r_ARQOS[3:0],m_axi_INPUT_r_ARREADY,m_axi_INPUT_r_ARREGION[3:0],m_axi_INPUT_r_ARSIZE[2:0],m_axi_INPUT_r_ARVALID,m_axi_INPUT_r_AWADDR[63:0],m_axi_INPUT_r_AWBURST[1:0],m_axi_INPUT_r_AWCACHE[3:0],m_axi_INPUT_r_AWID[0:0],m_axi_INPUT_r_AWLEN[7:0],m_axi_INPUT_r_AWLOCK[1:0],m_axi_INPUT_r_AWPROT[2:0],m_axi_INPUT_r_AWQOS[3:0],m_axi_INPUT_r_AWREADY,m_axi_INPUT_r_AWREGION[3:0],m_axi_INPUT_r_AWSIZE[2:0],m_axi_INPUT_r_AWVALID,m_axi_INPUT_r_BID[0:0],m_axi_INPUT_r_BREADY,m_axi_INPUT_r_BRESP[1:0],m_axi_INPUT_r_BVALID,m_axi_INPUT_r_RDATA[31:0],m_axi_INPUT_r_RID[0:0],m_axi_INPUT_r_RLAST,m_axi_INPUT_r_RREADY,m_axi_INPUT_r_RRESP[1:0],m_axi_INPUT_r_RVALID,m_axi_INPUT_r_WDATA[31:0],m_axi_INPUT_r_WID[0:0],m_axi_INPUT_r_WLAST,m_axi_INPUT_r_WREADY,m_axi_INPUT_r_WSTRB[3:0],m_axi_INPUT_r_WVALID,m_axi_OUTPUT_r_ARADDR[63:0],m_axi_OUTPUT_r_ARBURST[1:0],m_axi_OUTPUT_r_ARCACHE[3:0],m_axi_OUTPUT_r_ARID[0:0],m_axi_OUTPUT_r_ARLEN[7:0],m_axi_OUTPUT_r_ARLOCK[1:0],m_axi_OUTPUT_r_ARPROT[2:0],m_axi_OUTPUT_r_ARQOS[3:0],m_axi_OUTPUT_r_ARREADY,m_axi_OUTPUT_r_ARREGION[3:0],m_axi_OUTPUT_r_ARSIZE[2:0],m_axi_OUTPUT_r_ARVALID,m_axi_OUTPUT_r_AWADDR[63:0],m_axi_OUTPUT_r_AWBURST[1:0],m_axi_OUTPUT_r_AWCACHE[3:0],m_axi_OUTPUT_r_AWID[0:0],m_axi_OUTPUT_r_AWLEN[7:0],m_axi_OUTPUT_r_AWLOCK[1:0],m_axi_OUTPUT_r_AWPROT[2:0],m_axi_OUTPUT_r_AWQOS[3:0],m_axi_OUTPUT_r_AWREADY,m_axi_OUTPUT_r_AWREGION[3:0],m_axi_OUTPUT_r_AWSIZE[2:0],m_axi_OUTPUT_r_AWVALID,m_axi_OUTPUT_r_BID[0:0],m_axi_OUTPUT_r_BREADY,m_axi_OUTPUT_r_BRESP[1:0],m_axi_OUTPUT_r_BVALID,m_axi_OUTPUT_r_RDATA[31:0],m_axi_OUTPUT_r_RID[0:0],m_axi_OUTPUT_r_RLAST,m_axi_OUTPUT_r_RREADY,m_axi_OUTPUT_r_RRESP[1:0],m_axi_OUTPUT_r_RVALID,m_axi_OUTPUT_r_WDATA[31:0],m_axi_OUTPUT_r_WID[0:0],m_axi_OUTPUT_r_WLAST,m_axi_OUTPUT_r_WREADY,m_axi_OUTPUT_r_WSTRB[3:0],m_axi_OUTPUT_r_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_CTRL_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_CTRL_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_CTRL_ARADDR : signal is "XIL_INTERFACENAME s_axi_CTRL, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 96968727, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_CTRL_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL ARREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL ARVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL AWADDR";
  attribute X_INTERFACE_INFO of s_axi_CTRL_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL AWREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL AWVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL BREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL BRESP";
  attribute X_INTERFACE_INFO of s_axi_CTRL_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL BVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RDATA";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RRESP";
  attribute X_INTERFACE_INFO of s_axi_CTRL_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL RVALID";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WDATA";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WREADY";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WSTRB";
  attribute X_INTERFACE_INFO of s_axi_CTRL_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_CTRL WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_CTRL:m_axi_INPUT_r:m_axi_OUTPUT_r, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 96968727, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARADDR";
  attribute X_INTERFACE_MODE of m_axi_INPUT_r_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_INPUT_r_ARADDR : signal is "XIL_INTERFACENAME m_axi_INPUT_r, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 96968727, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARBURST";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARLEN";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARPROT";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARQOS";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARREADY";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARREGION";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r ARVALID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWADDR";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWBURST";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWLEN";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWPROT";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWQOS";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWREADY";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWREGION";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r AWVALID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r BID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r BREADY";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r BRESP";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r BVALID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r RDATA";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r RID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r RLAST";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r RREADY";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r RRESP";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r RVALID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r WDATA";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r WID";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r WLAST";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r WREADY";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r WSTRB";
  attribute X_INTERFACE_INFO of m_axi_INPUT_r_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_INPUT_r WVALID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARADDR";
  attribute X_INTERFACE_MODE of m_axi_OUTPUT_r_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_OUTPUT_r_ARADDR : signal is "XIL_INTERFACENAME m_axi_OUTPUT_r, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 96968727, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARBURST";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARLEN";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARPROT";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARQOS";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARREADY";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARREGION";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r ARVALID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWADDR";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWBURST";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWLEN";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWPROT";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWQOS";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWREADY";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWREGION";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r AWVALID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r BID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r BREADY";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r BRESP";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r BVALID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r RDATA";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r RID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r RLAST";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r RREADY";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r RRESP";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r RVALID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r WDATA";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r WID";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r WLAST";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r WREADY";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r WSTRB";
  attribute X_INTERFACE_INFO of m_axi_OUTPUT_r_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_OUTPUT_r WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "forward,Vivado 2025.1";
begin
end;
