// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module forward_forward_Pipeline_VITIS_LOOP_41_2_VITIS_LOOP_43_35 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rnn_output_address0,
        rnn_output_ce0,
        rnn_output_q0,
        temp_3_address0,
        temp_3_ce0,
        temp_3_we0,
        temp_3_d0,
        grp_fu_806_p_din0,
        grp_fu_806_p_din1,
        grp_fu_806_p_opcode,
        grp_fu_806_p_dout0,
        grp_fu_806_p_ce,
        grp_fu_810_p_din0,
        grp_fu_810_p_din1,
        grp_fu_810_p_dout0,
        grp_fu_810_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] rnn_output_address0;
output   rnn_output_ce0;
input  [31:0] rnn_output_q0;
output  [2:0] temp_3_address0;
output   temp_3_ce0;
output   temp_3_we0;
output  [31:0] temp_3_d0;
output  [31:0] grp_fu_806_p_din0;
output  [31:0] grp_fu_806_p_din1;
output  [0:0] grp_fu_806_p_opcode;
input  [31:0] grp_fu_806_p_dout0;
output   grp_fu_806_p_ce;
output  [31:0] grp_fu_810_p_din0;
output  [31:0] grp_fu_810_p_din1;
input  [31:0] grp_fu_810_p_dout0;
output   grp_fu_810_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln41_reg_284;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] CLASSIFIER_WEIGHTS_TRANSPOSED_address0;
wire   [31:0] CLASSIFIER_WEIGHTS_TRANSPOSED_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln41_fu_134_p2;
wire   [0:0] icmp_ln43_fu_158_p2;
reg   [0:0] icmp_ln43_reg_288;
reg   [0:0] icmp_ln43_reg_288_pp0_iter1_reg;
wire   [0:0] icmp_ln43_1_fu_219_p2;
reg   [0:0] icmp_ln43_1_reg_303;
reg   [0:0] icmp_ln43_1_reg_303_pp0_iter1_reg;
reg   [2:0] temp_3_addr_reg_307;
reg   [2:0] temp_3_addr_reg_307_pp0_iter1_reg;
reg   [31:0] rnn_output_load_reg_312;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] CLASSIFIER_WEIGHTS_TRANSPOSED_load_reg_317;
reg   [31:0] mul_i1_reg_322;
wire   [31:0] select_ln41_1_fu_243_p3;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln44_fu_208_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln43_fu_189_p1;
wire   [63:0] zext_ln41_fu_180_p1;
reg   [31:0] run_sum_fu_48;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [6:0] j_fu_52;
wire   [6:0] add_ln43_fu_213_p2;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_fu_56;
wire   [3:0] select_ln41_2_fu_172_p3;
reg   [3:0] ap_sig_allocacmp_i_load;
reg   [9:0] indvar_flatten34_fu_60;
wire   [9:0] add_ln41_fu_140_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten34_load;
reg    rnn_output_ce0_local;
reg    CLASSIFIER_WEIGHTS_TRANSPOSED_ce0_local;
reg    temp_3_we0_local;
reg    temp_3_ce0_local;
wire    ap_block_pp0_stage2;
wire   [3:0] add_ln41_1_fu_152_p2;
wire   [6:0] select_ln41_fu_164_p3;
wire   [9:0] tmp_6_fu_194_p3;
wire   [9:0] zext_ln43_1_fu_185_p1;
wire   [9:0] add_ln44_fu_202_p2;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
wire    ap_block_pp0_stage3_11001;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 run_sum_fu_48 = 32'd0;
#0 j_fu_52 = 7'd0;
#0 i_fu_56 = 4'd0;
#0 indvar_flatten34_fu_60 = 10'd0;
#0 ap_done_reg = 1'b0;
end

forward_forward_Pipeline_VITIS_LOOP_41_2_VITIS_LOOP_43_35_CLASSIFIER_WEIGHTS_TRANSPOSEe0 #(
    .DataWidth( 32 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
CLASSIFIER_WEIGHTS_TRANSPOSED_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CLASSIFIER_WEIGHTS_TRANSPOSED_address0),
    .ce0(CLASSIFIER_WEIGHTS_TRANSPOSED_ce0_local),
    .q0(CLASSIFIER_WEIGHTS_TRANSPOSED_q0)
);

forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_56 <= select_ln41_2_fu_172_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten34_fu_60 <= add_ln41_fu_140_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten34_fu_60 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_52 <= add_ln43_fu_213_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_52 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            run_sum_fu_48 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            run_sum_fu_48 <= grp_fu_806_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        CLASSIFIER_WEIGHTS_TRANSPOSED_load_reg_317 <= CLASSIFIER_WEIGHTS_TRANSPOSED_q0;
        rnn_output_load_reg_312 <= rnn_output_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln41_reg_284 <= icmp_ln41_fu_134_p2;
        icmp_ln43_1_reg_303 <= icmp_ln43_1_fu_219_p2;
        icmp_ln43_1_reg_303_pp0_iter1_reg <= icmp_ln43_1_reg_303;
        icmp_ln43_reg_288 <= icmp_ln43_fu_158_p2;
        icmp_ln43_reg_288_pp0_iter1_reg <= icmp_ln43_reg_288;
        mul_i1_reg_322 <= grp_fu_810_p_dout0;
        temp_3_addr_reg_307 <= zext_ln41_fu_180_p1;
        temp_3_addr_reg_307_pp0_iter1_reg <= temp_3_addr_reg_307;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CLASSIFIER_WEIGHTS_TRANSPOSED_ce0_local = 1'b1;
    end else begin
        CLASSIFIER_WEIGHTS_TRANSPOSED_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_284 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_284 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten34_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten34_load = indvar_flatten34_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rnn_output_ce0_local = 1'b1;
    end else begin
        rnn_output_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_3_ce0_local = 1'b1;
    end else begin
        temp_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_1_reg_303_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_3_we0_local = 1'b1;
    end else begin
        temp_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CLASSIFIER_WEIGHTS_TRANSPOSED_address0 = zext_ln44_fu_208_p1;

assign add_ln41_1_fu_152_p2 = (ap_sig_allocacmp_i_load + 4'd1);

assign add_ln41_fu_140_p2 = (ap_sig_allocacmp_indvar_flatten34_load + 10'd1);

assign add_ln43_fu_213_p2 = (select_ln41_fu_164_p3 + 7'd1);

assign add_ln44_fu_202_p2 = (tmp_6_fu_194_p3 + zext_ln43_1_fu_185_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign grp_fu_806_p_ce = 1'b1;

assign grp_fu_806_p_din0 = select_ln41_1_fu_243_p3;

assign grp_fu_806_p_din1 = mul_i1_reg_322;

assign grp_fu_806_p_opcode = 2'd0;

assign grp_fu_810_p_ce = 1'b1;

assign grp_fu_810_p_din0 = rnn_output_load_reg_312;

assign grp_fu_810_p_din1 = CLASSIFIER_WEIGHTS_TRANSPOSED_load_reg_317;

assign icmp_ln41_fu_134_p2 = ((ap_sig_allocacmp_indvar_flatten34_load == 10'd800) ? 1'b1 : 1'b0);

assign icmp_ln43_1_fu_219_p2 = ((add_ln43_fu_213_p2 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_158_p2 = ((ap_sig_allocacmp_j_load == 7'd100) ? 1'b1 : 1'b0);

assign rnn_output_address0 = zext_ln43_fu_189_p1;

assign rnn_output_ce0 = rnn_output_ce0_local;

assign select_ln41_1_fu_243_p3 = ((icmp_ln43_reg_288_pp0_iter1_reg[0:0] == 1'b1) ? 32'd0 : run_sum_fu_48);

assign select_ln41_2_fu_172_p3 = ((icmp_ln43_fu_158_p2[0:0] == 1'b1) ? add_ln41_1_fu_152_p2 : ap_sig_allocacmp_i_load);

assign select_ln41_fu_164_p3 = ((icmp_ln43_fu_158_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign temp_3_address0 = temp_3_addr_reg_307_pp0_iter1_reg;

assign temp_3_ce0 = temp_3_ce0_local;

assign temp_3_d0 = grp_fu_806_p_dout0;

assign temp_3_we0 = temp_3_we0_local;

assign tmp_6_fu_194_p3 = {{select_ln41_fu_164_p3}, {3'd0}};

assign zext_ln41_fu_180_p1 = select_ln41_2_fu_172_p3;

assign zext_ln43_1_fu_185_p1 = select_ln41_2_fu_172_p3;

assign zext_ln43_fu_189_p1 = select_ln41_fu_164_p3;

assign zext_ln44_fu_208_p1 = add_ln44_fu_202_p2;

endmodule //forward_forward_Pipeline_VITIS_LOOP_41_2_VITIS_LOOP_43_35
