// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module forward_forward_Pipeline_VITIS_LOOP_152_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_OUTPUT_r_0_AWVALID,
        m_axi_OUTPUT_r_0_AWREADY,
        m_axi_OUTPUT_r_0_AWADDR,
        m_axi_OUTPUT_r_0_AWID,
        m_axi_OUTPUT_r_0_AWLEN,
        m_axi_OUTPUT_r_0_AWSIZE,
        m_axi_OUTPUT_r_0_AWBURST,
        m_axi_OUTPUT_r_0_AWLOCK,
        m_axi_OUTPUT_r_0_AWCACHE,
        m_axi_OUTPUT_r_0_AWPROT,
        m_axi_OUTPUT_r_0_AWQOS,
        m_axi_OUTPUT_r_0_AWREGION,
        m_axi_OUTPUT_r_0_AWUSER,
        m_axi_OUTPUT_r_0_WVALID,
        m_axi_OUTPUT_r_0_WREADY,
        m_axi_OUTPUT_r_0_WDATA,
        m_axi_OUTPUT_r_0_WSTRB,
        m_axi_OUTPUT_r_0_WLAST,
        m_axi_OUTPUT_r_0_WID,
        m_axi_OUTPUT_r_0_WUSER,
        m_axi_OUTPUT_r_0_ARVALID,
        m_axi_OUTPUT_r_0_ARREADY,
        m_axi_OUTPUT_r_0_ARADDR,
        m_axi_OUTPUT_r_0_ARID,
        m_axi_OUTPUT_r_0_ARLEN,
        m_axi_OUTPUT_r_0_ARSIZE,
        m_axi_OUTPUT_r_0_ARBURST,
        m_axi_OUTPUT_r_0_ARLOCK,
        m_axi_OUTPUT_r_0_ARCACHE,
        m_axi_OUTPUT_r_0_ARPROT,
        m_axi_OUTPUT_r_0_ARQOS,
        m_axi_OUTPUT_r_0_ARREGION,
        m_axi_OUTPUT_r_0_ARUSER,
        m_axi_OUTPUT_r_0_RVALID,
        m_axi_OUTPUT_r_0_RREADY,
        m_axi_OUTPUT_r_0_RDATA,
        m_axi_OUTPUT_r_0_RLAST,
        m_axi_OUTPUT_r_0_RID,
        m_axi_OUTPUT_r_0_RFIFONUM,
        m_axi_OUTPUT_r_0_RUSER,
        m_axi_OUTPUT_r_0_RRESP,
        m_axi_OUTPUT_r_0_BVALID,
        m_axi_OUTPUT_r_0_BREADY,
        m_axi_OUTPUT_r_0_BRESP,
        m_axi_OUTPUT_r_0_BID,
        m_axi_OUTPUT_r_0_BUSER,
        in_mult_weights_address0,
        in_mult_weights_ce0,
        in_mult_weights_q0,
        p_cast1_cast,
        h_t_mult_weights_address0,
        h_t_mult_weights_ce0,
        h_t_mult_weights_q0,
        p_cast2_cast,
        temp_1_address0,
        temp_1_ce0,
        temp_1_q0,
        p_cast3_cast,
        p_cast4_cast,
        p_cast5_cast,
        p_cast6_cast,
        h_t_address0,
        h_t_ce0,
        h_t_q0,
        sext_ln133,
        temp_2_address0,
        temp_2_ce0,
        temp_2_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 7'd1;
parameter    ap_ST_fsm_pp0_stage1 = 7'd2;
parameter    ap_ST_fsm_pp0_stage2 = 7'd4;
parameter    ap_ST_fsm_pp0_stage3 = 7'd8;
parameter    ap_ST_fsm_pp0_stage4 = 7'd16;
parameter    ap_ST_fsm_pp0_stage5 = 7'd32;
parameter    ap_ST_fsm_pp0_stage6 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_OUTPUT_r_0_AWVALID;
input   m_axi_OUTPUT_r_0_AWREADY;
output  [63:0] m_axi_OUTPUT_r_0_AWADDR;
output  [0:0] m_axi_OUTPUT_r_0_AWID;
output  [31:0] m_axi_OUTPUT_r_0_AWLEN;
output  [2:0] m_axi_OUTPUT_r_0_AWSIZE;
output  [1:0] m_axi_OUTPUT_r_0_AWBURST;
output  [1:0] m_axi_OUTPUT_r_0_AWLOCK;
output  [3:0] m_axi_OUTPUT_r_0_AWCACHE;
output  [2:0] m_axi_OUTPUT_r_0_AWPROT;
output  [3:0] m_axi_OUTPUT_r_0_AWQOS;
output  [3:0] m_axi_OUTPUT_r_0_AWREGION;
output  [0:0] m_axi_OUTPUT_r_0_AWUSER;
output   m_axi_OUTPUT_r_0_WVALID;
input   m_axi_OUTPUT_r_0_WREADY;
output  [31:0] m_axi_OUTPUT_r_0_WDATA;
output  [3:0] m_axi_OUTPUT_r_0_WSTRB;
output   m_axi_OUTPUT_r_0_WLAST;
output  [0:0] m_axi_OUTPUT_r_0_WID;
output  [0:0] m_axi_OUTPUT_r_0_WUSER;
output   m_axi_OUTPUT_r_0_ARVALID;
input   m_axi_OUTPUT_r_0_ARREADY;
output  [63:0] m_axi_OUTPUT_r_0_ARADDR;
output  [0:0] m_axi_OUTPUT_r_0_ARID;
output  [31:0] m_axi_OUTPUT_r_0_ARLEN;
output  [2:0] m_axi_OUTPUT_r_0_ARSIZE;
output  [1:0] m_axi_OUTPUT_r_0_ARBURST;
output  [1:0] m_axi_OUTPUT_r_0_ARLOCK;
output  [3:0] m_axi_OUTPUT_r_0_ARCACHE;
output  [2:0] m_axi_OUTPUT_r_0_ARPROT;
output  [3:0] m_axi_OUTPUT_r_0_ARQOS;
output  [3:0] m_axi_OUTPUT_r_0_ARREGION;
output  [0:0] m_axi_OUTPUT_r_0_ARUSER;
input   m_axi_OUTPUT_r_0_RVALID;
output   m_axi_OUTPUT_r_0_RREADY;
input  [31:0] m_axi_OUTPUT_r_0_RDATA;
input   m_axi_OUTPUT_r_0_RLAST;
input  [0:0] m_axi_OUTPUT_r_0_RID;
input  [8:0] m_axi_OUTPUT_r_0_RFIFONUM;
input  [0:0] m_axi_OUTPUT_r_0_RUSER;
input  [1:0] m_axi_OUTPUT_r_0_RRESP;
input   m_axi_OUTPUT_r_0_BVALID;
output   m_axi_OUTPUT_r_0_BREADY;
input  [1:0] m_axi_OUTPUT_r_0_BRESP;
input  [0:0] m_axi_OUTPUT_r_0_BID;
input  [0:0] m_axi_OUTPUT_r_0_BUSER;
output  [6:0] in_mult_weights_address0;
output   in_mult_weights_ce0;
input  [31:0] in_mult_weights_q0;
input  [61:0] p_cast1_cast;
output  [6:0] h_t_mult_weights_address0;
output   h_t_mult_weights_ce0;
input  [31:0] h_t_mult_weights_q0;
input  [61:0] p_cast2_cast;
output  [6:0] temp_1_address0;
output   temp_1_ce0;
input  [31:0] temp_1_q0;
input  [61:0] p_cast3_cast;
input  [61:0] p_cast4_cast;
input  [61:0] p_cast5_cast;
input  [61:0] p_cast6_cast;
output  [6:0] h_t_address0;
output   h_t_ce0;
input  [31:0] h_t_q0;
input  [61:0] sext_ln133;
output  [6:0] temp_2_address0;
output   temp_2_ce0;
input  [31:0] temp_2_q0;

reg ap_idle;
reg m_axi_OUTPUT_r_0_AWVALID;
reg[63:0] m_axi_OUTPUT_r_0_AWADDR;
reg m_axi_OUTPUT_r_0_WVALID;
reg[31:0] m_axi_OUTPUT_r_0_WDATA;
reg m_axi_OUTPUT_r_0_BREADY;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage6;
reg   [0:0] icmp_ln152_reg_452;
reg    ap_block_state7_io_grp10;
reg    ap_block_pp0_stage6_subdone_grp10_done_reg;
reg    ap_block_pp0_stage6_subdone_grp10;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_state7_io_grp11;
reg    ap_block_pp0_stage6_subdone_grp11_done_reg;
reg    ap_block_pp0_stage6_subdone_grp11;
reg    ap_block_pp0_stage6_subdone_grp21_done_reg;
reg    ap_block_pp0_stage6_subdone_grp21;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_condition_exit_pp0_iter0_stage6;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] RNN_INPUT_BIASES_address0;
wire   [31:0] RNN_INPUT_BIASES_q0;
wire   [6:0] RNN_HIDDEN_BIASES_address0;
wire   [31:0] RNN_HIDDEN_BIASES_q0;
reg    OUTPUT_r_blk_n_AW;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    OUTPUT_r_blk_n_W;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
reg    ap_block_pp0_stage2_subdone_grp2_done_reg;
reg    ap_block_pp0_stage2_subdone_grp2;
reg    ap_block_pp0_stage2_subdone;
reg    OUTPUT_r_blk_n_B;
wire    ap_block_pp0_stage0_grp12;
reg    ap_block_pp0_stage0_subdone_grp12_done_reg;
reg    ap_block_pp0_stage0_subdone_grp12;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage2_grp3;
reg    ap_block_pp0_stage2_subdone_grp3_done_reg;
reg    ap_block_pp0_stage2_subdone_grp3;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp4;
reg    ap_block_pp0_stage3_subdone_grp4_done_reg;
reg    ap_block_pp0_stage3_subdone_grp4;
reg    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage1_grp15;
reg    ap_block_pp0_stage1_subdone_grp15_done_reg;
reg    ap_block_pp0_stage1_subdone_grp15;
wire    ap_block_pp0_stage3_grp5;
reg    ap_block_pp0_stage3_subdone_grp5_done_reg;
reg    ap_block_pp0_stage3_subdone_grp5;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp6;
reg    ap_block_pp0_stage4_subdone_grp6_done_reg;
reg    ap_block_pp0_stage4_subdone_grp6;
reg    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage2_grp17;
reg    ap_block_pp0_stage2_subdone_grp17_done_reg;
reg    ap_block_pp0_stage2_subdone_grp17;
wire    ap_block_pp0_stage4_grp7;
reg    ap_block_pp0_stage4_subdone_grp7_done_reg;
reg    ap_block_pp0_stage4_subdone_grp7;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_grp8;
reg    ap_block_pp0_stage5_subdone_grp8_done_reg;
reg    ap_block_pp0_stage5_subdone_grp8;
reg    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage3_grp18;
reg    ap_block_pp0_stage3_subdone_grp18_done_reg;
reg    ap_block_pp0_stage3_subdone_grp18;
wire    ap_block_pp0_stage5_grp9;
reg    ap_block_pp0_stage5_subdone_grp9_done_reg;
reg    ap_block_pp0_stage5_subdone_grp9;
wire    ap_block_pp0_stage6_grp10;
wire    ap_block_pp0_stage4_grp19;
reg    ap_block_pp0_stage4_subdone_grp19_done_reg;
reg    ap_block_pp0_stage4_subdone_grp19;
wire    ap_block_pp0_stage6_grp11;
wire    ap_block_pp0_stage0_grp13;
reg    ap_block_pp0_stage0_subdone_grp13_done_reg;
reg    ap_block_pp0_stage0_subdone_grp13;
wire    ap_block_pp0_stage5_grp20;
reg    ap_block_pp0_stage5_subdone_grp20_done_reg;
reg    ap_block_pp0_stage5_subdone_grp20;
wire    ap_block_pp0_stage0_grp14;
reg    ap_block_pp0_stage0_subdone_grp14_done_reg;
reg    ap_block_pp0_stage0_subdone_grp14;
wire    ap_block_pp0_stage1_grp16;
reg    ap_block_pp0_stage1_subdone_grp16_done_reg;
reg    ap_block_pp0_stage1_subdone_grp16;
wire    ap_block_pp0_stage6_grp21;
wire   [0:0] icmp_ln152_fu_273_p2;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] OUTPUT_r_addr_reg_461;
reg   [63:0] OUTPUT_r_addr_1_reg_473;
reg   [63:0] OUTPUT_r_addr_2_reg_485;
reg   [63:0] OUTPUT_r_addr_3_reg_497;
reg   [63:0] OUTPUT_r_addr_4_reg_509;
reg   [63:0] OUTPUT_r_addr_5_reg_521;
reg   [63:0] OUTPUT_r_addr_6_reg_533;
reg   [31:0] in_mult_weights_load_reg_540;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg   [31:0] h_t_mult_weights_load_reg_545;
reg   [31:0] temp_1_load_reg_550;
reg   [31:0] RNN_INPUT_BIASES_load_reg_555;
reg   [31:0] RNN_HIDDEN_BIASES_load_reg_560;
reg   [31:0] temp_2_load_reg_565;
reg   [31:0] h_t_load_reg_570;
reg    ap_block_pp0_stage1_11001_grp16;
wire   [63:0] zext_ln152_fu_285_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln153_fu_306_p1;
wire  signed [63:0] sext_ln154_fu_322_p1;
wire  signed [63:0] sext_ln155_fu_338_p1;
wire  signed [63:0] sext_ln156_fu_354_p1;
wire  signed [63:0] sext_ln157_fu_370_p1;
wire  signed [63:0] sext_ln158_fu_386_p1;
wire  signed [63:0] sext_ln159_fu_402_p1;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_state3_io_grp3;
reg    ap_block_pp0_stage2_11001_grp3;
reg    ap_block_state4_io_grp5;
reg    ap_block_pp0_stage3_11001_grp5;
reg    ap_block_state5_io_grp7;
reg    ap_block_pp0_stage4_11001_grp7;
reg    ap_block_state6_io_grp9;
reg    ap_block_pp0_stage5_11001_grp9;
reg    ap_block_pp0_stage6_11001_grp11;
reg    ap_block_pp0_stage0_11001_grp14;
reg    ap_block_state3_io_grp2;
reg    ap_block_pp0_stage2_11001_grp2;
wire   [31:0] bitcast_ln153_fu_417_p1;
wire    ap_block_pp0_stage2_01001_grp2;
reg    ap_block_state4_io_grp4;
reg    ap_block_pp0_stage3_11001_grp4;
wire   [31:0] bitcast_ln154_fu_421_p1;
wire    ap_block_pp0_stage3_01001_grp4;
reg    ap_block_state5_io_grp6;
reg    ap_block_pp0_stage4_11001_grp6;
wire   [31:0] bitcast_ln155_fu_425_p1;
wire    ap_block_pp0_stage4_01001_grp6;
reg    ap_block_state6_io_grp8;
reg    ap_block_pp0_stage5_11001_grp8;
wire   [31:0] bitcast_ln156_fu_429_p1;
wire    ap_block_pp0_stage5_01001_grp8;
reg    ap_block_pp0_stage6_11001_grp10;
wire   [31:0] bitcast_ln157_fu_433_p1;
wire    ap_block_pp0_stage6_01001_grp10;
reg    ap_block_pp0_stage0_11001_grp13;
wire   [31:0] bitcast_ln158_fu_437_p1;
wire    ap_block_pp0_stage0_01001_grp13;
wire   [31:0] bitcast_ln159_fu_441_p1;
wire    ap_block_pp0_stage1_01001_grp16;
reg    ap_block_pp0_stage0_11001_grp12;
reg    ap_block_pp0_stage1_11001_grp15;
reg    ap_block_pp0_stage2_11001_grp17;
reg    ap_block_pp0_stage3_11001_grp18;
reg    ap_block_pp0_stage4_11001_grp19;
reg    ap_block_pp0_stage5_11001_grp20;
reg    ap_block_pp0_stage6_11001_grp21;
reg   [6:0] j_fu_80;
wire   [6:0] add_ln152_fu_279_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_1;
reg    in_mult_weights_ce0_local;
reg    h_t_mult_weights_ce0_local;
reg    temp_1_ce0_local;
reg    RNN_INPUT_BIASES_ce0_local;
reg    RNN_HIDDEN_BIASES_ce0_local;
reg    temp_2_ce0_local;
reg    h_t_ce0_local;
wire   [62:0] zext_ln152_1_fu_296_p1;
wire  signed [62:0] p_cast1_cast_cast_fu_261_p1;
wire   [62:0] add_ln153_fu_300_p2;
wire  signed [62:0] p_cast2_cast_cast_fu_257_p1;
wire   [62:0] add_ln154_fu_316_p2;
wire  signed [62:0] p_cast3_cast_cast_fu_253_p1;
wire   [62:0] add_ln155_fu_332_p2;
wire  signed [62:0] p_cast4_cast_cast_fu_249_p1;
wire   [62:0] add_ln156_fu_348_p2;
wire  signed [62:0] p_cast5_cast_cast_fu_245_p1;
wire   [62:0] add_ln157_fu_364_p2;
wire  signed [62:0] p_cast6_cast_cast_fu_241_p1;
wire   [62:0] add_ln158_fu_380_p2;
wire  signed [62:0] sext_ln133_cast_fu_237_p1;
wire   [62:0] add_ln159_fu_396_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [6:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp0_stage6_subdone_grp10_done_reg = 1'b0;
#0 ap_block_pp0_stage6_subdone_grp11_done_reg = 1'b0;
#0 ap_block_pp0_stage6_subdone_grp21_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp12_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp15_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage4_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp17_done_reg = 1'b0;
#0 ap_block_pp0_stage4_subdone_grp7_done_reg = 1'b0;
#0 ap_block_pp0_stage5_subdone_grp8_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp18_done_reg = 1'b0;
#0 ap_block_pp0_stage5_subdone_grp9_done_reg = 1'b0;
#0 ap_block_pp0_stage4_subdone_grp19_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp13_done_reg = 1'b0;
#0 ap_block_pp0_stage5_subdone_grp20_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp14_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp16_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 j_fu_80 = 7'd0;
#0 ap_done_reg = 1'b0;
end

forward_forward_Pipeline_VITIS_LOOP_152_5_RNN_INPUT_BIASES_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
RNN_INPUT_BIASES_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RNN_INPUT_BIASES_address0),
    .ce0(RNN_INPUT_BIASES_ce0_local),
    .q0(RNN_INPUT_BIASES_q0)
);

forward_forward_Pipeline_VITIS_LOOP_152_5_RNN_HIDDEN_BIASES_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
RNN_HIDDEN_BIASES_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RNN_HIDDEN_BIASES_address0),
    .ce0(RNN_HIDDEN_BIASES_ce0_local),
    .q0(RNN_HIDDEN_BIASES_q0)
);

forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage6),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp12_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp12_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp12)) begin
                ap_block_pp0_stage0_subdone_grp12_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp13_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp13_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp13)) begin
                ap_block_pp0_stage0_subdone_grp13_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp14_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp14_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp14)) begin
                ap_block_pp0_stage0_subdone_grp14_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp15_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp15_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp15)) begin
                ap_block_pp0_stage1_subdone_grp15_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp16_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp16_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp16)) begin
                ap_block_pp0_stage1_subdone_grp16_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp17_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp17_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp17)) begin
                ap_block_pp0_stage2_subdone_grp17_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp2)) begin
                ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp3)) begin
                ap_block_pp0_stage2_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp18_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp18_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp18)) begin
                ap_block_pp0_stage3_subdone_grp18_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp4)) begin
                ap_block_pp0_stage3_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp5)) begin
                ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage4_subdone_grp19_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage4)) begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_block_pp0_stage4_subdone_grp19_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone_grp19)) begin
                ap_block_pp0_stage4_subdone_grp19_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage4_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage4)) begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_block_pp0_stage4_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone_grp6)) begin
                ap_block_pp0_stage4_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage4_subdone_grp7_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage4)) begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_block_pp0_stage4_subdone_grp7_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone_grp7)) begin
                ap_block_pp0_stage4_subdone_grp7_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage5_subdone_grp20_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage5)) begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_block_pp0_stage5_subdone_grp20_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage5_subdone_grp20)) begin
                ap_block_pp0_stage5_subdone_grp20_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage5_subdone_grp8_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage5)) begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_block_pp0_stage5_subdone_grp8_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage5_subdone_grp8)) begin
                ap_block_pp0_stage5_subdone_grp8_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage5_subdone_grp9_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage5)) begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_block_pp0_stage5_subdone_grp9_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage5_subdone_grp9)) begin
                ap_block_pp0_stage5_subdone_grp9_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage6_subdone_grp10_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_block_pp0_stage6_subdone_grp10_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage6_subdone_grp10)) begin
                ap_block_pp0_stage6_subdone_grp10_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage6_subdone_grp11_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_block_pp0_stage6_subdone_grp11_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage6_subdone_grp11)) begin
                ap_block_pp0_stage6_subdone_grp11_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage6_subdone_grp21_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_block_pp0_stage6_subdone_grp21_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage6_subdone_grp21)) begin
                ap_block_pp0_stage6_subdone_grp21_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage6)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln152_fu_273_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_80 <= add_ln152_fu_279_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_80 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        OUTPUT_r_addr_1_reg_473 <= sext_ln154_fu_322_p1;
        OUTPUT_r_addr_2_reg_485 <= sext_ln155_fu_338_p1;
        OUTPUT_r_addr_3_reg_497 <= sext_ln156_fu_354_p1;
        OUTPUT_r_addr_4_reg_509 <= sext_ln157_fu_370_p1;
        OUTPUT_r_addr_5_reg_521 <= sext_ln158_fu_386_p1;
        OUTPUT_r_addr_6_reg_533 <= sext_ln159_fu_402_p1;
        OUTPUT_r_addr_reg_461 <= sext_ln153_fu_306_p1;
        icmp_ln152_reg_452 <= icmp_ln152_fu_273_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        RNN_HIDDEN_BIASES_load_reg_560 <= RNN_HIDDEN_BIASES_q0;
        RNN_INPUT_BIASES_load_reg_555 <= RNN_INPUT_BIASES_q0;
        h_t_mult_weights_load_reg_545 <= h_t_mult_weights_q0;
        in_mult_weights_load_reg_540 <= in_mult_weights_q0;
        temp_1_load_reg_550 <= temp_1_q0;
        temp_2_load_reg_565 <= temp_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp16) & (1'b0 == ap_block_pp0_stage1_subdone_grp16_done_reg))) begin
        h_t_load_reg_570 <= h_t_q0;
    end
end

always @ (*) begin
    if ((((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_grp11) & (1'b0 == ap_block_pp0_stage6_subdone_grp11_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp9_done_reg) & (1'b0 == ap_block_pp0_stage5_grp9)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp7_done_reg) & (1'b0 == ap_block_pp0_stage4_grp7)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg) & (1'b0 == ap_block_pp0_stage3_grp5)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage2_grp3)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 
    == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg) & (1'b0 == ap_block_pp0_stage0_grp14)))) begin
        OUTPUT_r_blk_n_AW = m_axi_OUTPUT_r_0_AWREADY;
    end else begin
        OUTPUT_r_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_grp21) & (1'b0 == ap_block_pp0_stage6_subdone_grp21_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone_grp20_done_reg) & (1'b0 == ap_block_pp0_stage5_grp20)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone_grp19_done_reg) & (1'b0 == ap_block_pp0_stage4_grp19)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp18_done_reg) & (1'b0 == ap_block_pp0_stage3_grp18)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp17_done_reg) & (1'b0 == ap_block_pp0_stage2_grp17)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg) & (1'b0 == ap_block_pp0_stage0_grp12)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 
    == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp15_done_reg) & (1'b0 == ap_block_pp0_stage1_grp15)))) begin
        OUTPUT_r_blk_n_B = m_axi_OUTPUT_r_0_BVALID;
    end else begin
        OUTPUT_r_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp10_done_reg) & (1'b0 == ap_block_pp0_stage6_grp10)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp8_done_reg) & (1'b0 == ap_block_pp0_stage5_grp8)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp6_done_reg) & (1'b0 == ap_block_pp0_stage4_grp6)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg) & (1'b0 == ap_block_pp0_stage3_grp4)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage2_grp2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & 
    (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg) & (1'b0 == ap_block_pp0_stage0_grp13)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp16_done_reg) & (1'b0 == ap_block_pp0_stage1_grp16)))) begin
        OUTPUT_r_blk_n_W = m_axi_OUTPUT_r_0_WREADY;
    end else begin
        OUTPUT_r_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RNN_HIDDEN_BIASES_ce0_local = 1'b1;
    end else begin
        RNN_HIDDEN_BIASES_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RNN_INPUT_BIASES_ce0_local = 1'b1;
    end else begin
        RNN_INPUT_BIASES_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln152_reg_452 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone))) begin
        ap_condition_exit_pp0_iter0_stage6 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_80;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        h_t_ce0_local = 1'b1;
    end else begin
        h_t_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        h_t_mult_weights_ce0_local = 1'b1;
    end else begin
        h_t_mult_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_mult_weights_ce0_local = 1'b1;
    end else begin
        in_mult_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg))) begin
        m_axi_OUTPUT_r_0_AWADDR = OUTPUT_r_addr_6_reg_533;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp11) & (1'b0 == ap_block_pp0_stage6_subdone_grp11_done_reg))) begin
        m_axi_OUTPUT_r_0_AWADDR = OUTPUT_r_addr_5_reg_521;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp9) & (1'b0 == ap_block_pp0_stage5_subdone_grp9_done_reg))) begin
        m_axi_OUTPUT_r_0_AWADDR = OUTPUT_r_addr_4_reg_509;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp7) & (1'b0 == ap_block_pp0_stage4_subdone_grp7_done_reg))) begin
        m_axi_OUTPUT_r_0_AWADDR = OUTPUT_r_addr_3_reg_497;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg))) begin
        m_axi_OUTPUT_r_0_AWADDR = OUTPUT_r_addr_2_reg_485;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg))) begin
        m_axi_OUTPUT_r_0_AWADDR = OUTPUT_r_addr_1_reg_473;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg))) begin
        m_axi_OUTPUT_r_0_AWADDR = OUTPUT_r_addr_reg_461;
    end else begin
        m_axi_OUTPUT_r_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp11) & (1'b0 == ap_block_pp0_stage6_subdone_grp11_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp9) & (1'b0 == ap_block_pp0_stage5_subdone_grp9_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp7) & (1'b0 == ap_block_pp0_stage4_subdone_grp7_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg)) | ((icmp_ln152_reg_452 
    == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp14) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg)))) begin
        m_axi_OUTPUT_r_0_AWVALID = 1'b1;
    end else begin
        m_axi_OUTPUT_r_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001_grp21) & (1'b0 == ap_block_pp0_stage6_subdone_grp21_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001_grp20) & (1'b0 == ap_block_pp0_stage5_subdone_grp20_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001_grp19) & (1'b0 == ap_block_pp0_stage4_subdone_grp19_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp18) & (1'b0 == ap_block_pp0_stage3_subdone_grp18_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp17) & (1'b0 == ap_block_pp0_stage2_subdone_grp17_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp12) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg)) | ((ap_enable_reg_pp0_iter1 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp15) & (1'b0 == ap_block_pp0_stage1_subdone_grp15_done_reg)))) begin
        m_axi_OUTPUT_r_0_BREADY = 1'b1;
    end else begin
        m_axi_OUTPUT_r_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001_grp16) & (1'b0 == ap_block_pp0_stage1_subdone_grp16_done_reg))) begin
        m_axi_OUTPUT_r_0_WDATA = bitcast_ln159_fu_441_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg))) begin
        m_axi_OUTPUT_r_0_WDATA = bitcast_ln158_fu_437_p1;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp10_done_reg) & (1'b0 == ap_block_pp0_stage6_01001_grp10))) begin
        m_axi_OUTPUT_r_0_WDATA = bitcast_ln157_fu_433_p1;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_01001_grp8) & (1'b0 == ap_block_pp0_stage5_subdone_grp8_done_reg))) begin
        m_axi_OUTPUT_r_0_WDATA = bitcast_ln156_fu_429_p1;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_01001_grp6) & (1'b0 == ap_block_pp0_stage4_subdone_grp6_done_reg))) begin
        m_axi_OUTPUT_r_0_WDATA = bitcast_ln155_fu_425_p1;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg))) begin
        m_axi_OUTPUT_r_0_WDATA = bitcast_ln154_fu_421_p1;
    end else if (((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg))) begin
        m_axi_OUTPUT_r_0_WDATA = bitcast_ln153_fu_417_p1;
    end else begin
        m_axi_OUTPUT_r_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp10_done_reg) & (1'b0 == ap_block_pp0_stage6_11001_grp10)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp8) & (1'b0 == ap_block_pp0_stage5_subdone_grp8_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp6) & (1'b0 == ap_block_pp0_stage4_subdone_grp6_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)) | ((icmp_ln152_reg_452 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)) | ((ap_enable_reg_pp0_iter1 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp13) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp16) & (1'b0 == ap_block_pp0_stage1_subdone_grp16_done_reg)))) begin
        m_axi_OUTPUT_r_0_WVALID = 1'b1;
    end else begin
        m_axi_OUTPUT_r_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        temp_1_ce0_local = 1'b1;
    end else begin
        temp_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        temp_2_ce0_local = 1'b1;
    end else begin
        temp_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to1 == 1'b1) & (ap_start_int == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign RNN_HIDDEN_BIASES_address0 = zext_ln152_fu_285_p1;

assign RNN_INPUT_BIASES_address0 = zext_ln152_fu_285_p1;

assign add_ln152_fu_279_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign add_ln153_fu_300_p2 = ($signed(zext_ln152_1_fu_296_p1) + $signed(p_cast1_cast_cast_fu_261_p1));

assign add_ln154_fu_316_p2 = ($signed(zext_ln152_1_fu_296_p1) + $signed(p_cast2_cast_cast_fu_257_p1));

assign add_ln155_fu_332_p2 = ($signed(zext_ln152_1_fu_296_p1) + $signed(p_cast3_cast_cast_fu_253_p1));

assign add_ln156_fu_348_p2 = ($signed(zext_ln152_1_fu_296_p1) + $signed(p_cast4_cast_cast_fu_249_p1));

assign add_ln157_fu_364_p2 = ($signed(zext_ln152_1_fu_296_p1) + $signed(p_cast5_cast_cast_fu_245_p1));

assign add_ln158_fu_380_p2 = ($signed(zext_ln152_1_fu_296_p1) + $signed(p_cast6_cast_cast_fu_241_p1));

assign add_ln159_fu_396_p2 = ($signed(zext_ln152_1_fu_296_p1) + $signed(sext_ln133_cast_fu_237_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((m_axi_OUTPUT_r_0_WREADY == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg)) | ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg)) | ((m_axi_OUTPUT_r_0_AWREADY == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp12 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp13 = ((m_axi_OUTPUT_r_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp14 = ((m_axi_OUTPUT_r_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg));
end

assign ap_block_pp0_stage0_grp12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((m_axi_OUTPUT_r_0_WREADY == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg)) | ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg)) | ((m_axi_OUTPUT_r_0_AWREADY == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp12 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp12_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp13 = ((m_axi_OUTPUT_r_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp13_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp14 = ((m_axi_OUTPUT_r_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp14_done_reg));
end

assign ap_block_pp0_stage1_01001_grp16 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp15 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp15_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp16 = ((m_axi_OUTPUT_r_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp16_done_reg));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp16 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((m_axi_OUTPUT_r_0_WREADY == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone_grp16_done_reg)) | ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone_grp15_done_reg)))));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp15 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp15_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp16 = ((m_axi_OUTPUT_r_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp16_done_reg));
end

assign ap_block_pp0_stage2_01001_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp17 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp17_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp3 = ((1'b1 == ap_block_state3_io_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg));
end

assign ap_block_pp0_stage2_grp17 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp17_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state3_io_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state3_io_grp3) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg)))));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp17 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp17_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp2 = ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp3 = ((1'b1 == ap_block_state3_io_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp3_done_reg));
end

assign ap_block_pp0_stage3_01001_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp18 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp18_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp4 = ((1'b1 == ap_block_state4_io_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp5 = ((1'b1 == ap_block_state4_io_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg));
end

assign ap_block_pp0_stage3_grp18 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp18_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state4_io_grp4) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg)) | ((1'b1 == ap_block_state4_io_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)))));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp18 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp18_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp4 = ((1'b1 == ap_block_state4_io_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp5 = ((1'b1 == ap_block_state4_io_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg));
end

assign ap_block_pp0_stage4_01001_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001_grp19 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp19_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp6 = ((1'b1 == ap_block_state5_io_grp6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp7 = ((1'b1 == ap_block_state5_io_grp7) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp7_done_reg));
end

assign ap_block_pp0_stage4_grp19 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_grp6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp19_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state5_io_grp6) & (1'b0 == ap_block_pp0_stage4_subdone_grp6_done_reg)) | ((1'b1 == ap_block_state5_io_grp7) & (1'b0 == ap_block_pp0_stage4_subdone_grp7_done_reg)))));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone_grp19 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp19_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone_grp6 = ((1'b1 == ap_block_state5_io_grp6) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone_grp7 = ((1'b1 == ap_block_state5_io_grp7) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp7_done_reg));
end

assign ap_block_pp0_stage5_01001_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001_grp20 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp20_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage5_11001_grp8 = ((1'b1 == ap_block_state6_io_grp8) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp8_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage5_11001_grp9 = ((1'b1 == ap_block_state6_io_grp9) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp9_done_reg));
end

assign ap_block_pp0_stage5_grp20 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_grp8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp20_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state6_io_grp8) & (1'b0 == ap_block_pp0_stage5_subdone_grp8_done_reg)) | ((1'b1 == ap_block_state6_io_grp9) & (1'b0 == ap_block_pp0_stage5_subdone_grp9_done_reg)))));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone_grp20 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp20_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone_grp8 = ((1'b1 == ap_block_state6_io_grp8) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp8_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone_grp9 = ((1'b1 == ap_block_state6_io_grp9) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone_grp9_done_reg));
end

assign ap_block_pp0_stage6_01001_grp10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001_grp10 = ((1'b1 == ap_block_state7_io_grp10) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage6_11001_grp11 = ((1'b1 == ap_block_state7_io_grp11) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp11_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage6_11001_grp21 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp21_done_reg));
end

assign ap_block_pp0_stage6_grp10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_grp11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_grp21 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp21_done_reg)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b1 == ap_block_state7_io_grp10) & (1'b0 == ap_block_pp0_stage6_subdone_grp10_done_reg)) | ((1'b1 == ap_block_state7_io_grp11) & (1'b0 == ap_block_pp0_stage6_subdone_grp11_done_reg)))));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone_grp10 = ((1'b1 == ap_block_state7_io_grp10) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp10_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone_grp11 = ((1'b1 == ap_block_state7_io_grp11) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp11_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone_grp21 = ((m_axi_OUTPUT_r_0_BVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone_grp21_done_reg));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_io_grp2 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_io_grp3 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp4 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp5 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp6 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp7 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state6_io_grp8 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state6_io_grp9 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state7_io_grp10 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state7_io_grp11 = ((icmp_ln152_reg_452 == 1'd0) & (m_axi_OUTPUT_r_0_AWREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage6;

assign ap_ready = ap_ready_sig;

assign bitcast_ln153_fu_417_p1 = in_mult_weights_load_reg_540;

assign bitcast_ln154_fu_421_p1 = h_t_mult_weights_load_reg_545;

assign bitcast_ln155_fu_425_p1 = temp_1_load_reg_550;

assign bitcast_ln156_fu_429_p1 = RNN_INPUT_BIASES_load_reg_555;

assign bitcast_ln157_fu_433_p1 = RNN_HIDDEN_BIASES_load_reg_560;

assign bitcast_ln158_fu_437_p1 = temp_2_load_reg_565;

assign bitcast_ln159_fu_441_p1 = h_t_load_reg_570;

assign h_t_address0 = zext_ln152_fu_285_p1;

assign h_t_ce0 = h_t_ce0_local;

assign h_t_mult_weights_address0 = zext_ln152_fu_285_p1;

assign h_t_mult_weights_ce0 = h_t_mult_weights_ce0_local;

assign icmp_ln152_fu_273_p2 = ((ap_sig_allocacmp_j_1 == 7'd100) ? 1'b1 : 1'b0);

assign in_mult_weights_address0 = zext_ln152_fu_285_p1;

assign in_mult_weights_ce0 = in_mult_weights_ce0_local;

assign m_axi_OUTPUT_r_0_ARADDR = 64'd0;

assign m_axi_OUTPUT_r_0_ARBURST = 2'd0;

assign m_axi_OUTPUT_r_0_ARCACHE = 4'd0;

assign m_axi_OUTPUT_r_0_ARID = 1'd0;

assign m_axi_OUTPUT_r_0_ARLEN = 32'd0;

assign m_axi_OUTPUT_r_0_ARLOCK = 2'd0;

assign m_axi_OUTPUT_r_0_ARPROT = 3'd0;

assign m_axi_OUTPUT_r_0_ARQOS = 4'd0;

assign m_axi_OUTPUT_r_0_ARREGION = 4'd0;

assign m_axi_OUTPUT_r_0_ARSIZE = 3'd0;

assign m_axi_OUTPUT_r_0_ARUSER = 1'd0;

assign m_axi_OUTPUT_r_0_ARVALID = 1'b0;

assign m_axi_OUTPUT_r_0_AWBURST = 2'd0;

assign m_axi_OUTPUT_r_0_AWCACHE = 4'd0;

assign m_axi_OUTPUT_r_0_AWID = 1'd0;

assign m_axi_OUTPUT_r_0_AWLEN = 64'd1;

assign m_axi_OUTPUT_r_0_AWLOCK = 2'd0;

assign m_axi_OUTPUT_r_0_AWPROT = 3'd0;

assign m_axi_OUTPUT_r_0_AWQOS = 4'd0;

assign m_axi_OUTPUT_r_0_AWREGION = 4'd0;

assign m_axi_OUTPUT_r_0_AWSIZE = 3'd0;

assign m_axi_OUTPUT_r_0_AWUSER = 1'd0;

assign m_axi_OUTPUT_r_0_RREADY = 1'b0;

assign m_axi_OUTPUT_r_0_WID = 1'd0;

assign m_axi_OUTPUT_r_0_WLAST = 1'b0;

assign m_axi_OUTPUT_r_0_WSTRB = 4'd15;

assign m_axi_OUTPUT_r_0_WUSER = 1'd0;

assign p_cast1_cast_cast_fu_261_p1 = $signed(p_cast1_cast);

assign p_cast2_cast_cast_fu_257_p1 = $signed(p_cast2_cast);

assign p_cast3_cast_cast_fu_253_p1 = $signed(p_cast3_cast);

assign p_cast4_cast_cast_fu_249_p1 = $signed(p_cast4_cast);

assign p_cast5_cast_cast_fu_245_p1 = $signed(p_cast5_cast);

assign p_cast6_cast_cast_fu_241_p1 = $signed(p_cast6_cast);

assign sext_ln133_cast_fu_237_p1 = $signed(sext_ln133);

assign sext_ln153_fu_306_p1 = $signed(add_ln153_fu_300_p2);

assign sext_ln154_fu_322_p1 = $signed(add_ln154_fu_316_p2);

assign sext_ln155_fu_338_p1 = $signed(add_ln155_fu_332_p2);

assign sext_ln156_fu_354_p1 = $signed(add_ln156_fu_348_p2);

assign sext_ln157_fu_370_p1 = $signed(add_ln157_fu_364_p2);

assign sext_ln158_fu_386_p1 = $signed(add_ln158_fu_380_p2);

assign sext_ln159_fu_402_p1 = $signed(add_ln159_fu_396_p2);

assign temp_1_address0 = zext_ln152_fu_285_p1;

assign temp_1_ce0 = temp_1_ce0_local;

assign temp_2_address0 = zext_ln152_fu_285_p1;

assign temp_2_ce0 = temp_2_ce0_local;

assign zext_ln152_1_fu_296_p1 = ap_sig_allocacmp_j_1;

assign zext_ln152_fu_285_p1 = ap_sig_allocacmp_j_1;

endmodule //forward_forward_Pipeline_VITIS_LOOP_152_5
