// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module forward_forward_Pipeline_VITIS_LOOP_41_2_VITIS_LOOP_43_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        h_t_minus_1_address0,
        h_t_minus_1_ce0,
        h_t_minus_1_q0,
        h_t_mult_weights_address0,
        h_t_mult_weights_ce0,
        h_t_mult_weights_we0,
        h_t_mult_weights_d0,
        grp_fu_1626_p_din0,
        grp_fu_1626_p_din1,
        grp_fu_1626_p_dout0,
        grp_fu_1626_p_ce,
        grp_fu_1622_p_din0,
        grp_fu_1622_p_din1,
        grp_fu_1622_p_opcode,
        grp_fu_1622_p_dout0,
        grp_fu_1622_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] h_t_minus_1_address0;
output   h_t_minus_1_ce0;
input  [31:0] h_t_minus_1_q0;
output  [6:0] h_t_mult_weights_address0;
output   h_t_mult_weights_ce0;
output   h_t_mult_weights_we0;
output  [31:0] h_t_mult_weights_d0;
output  [31:0] grp_fu_1626_p_din0;
output  [31:0] grp_fu_1626_p_din1;
input  [31:0] grp_fu_1626_p_dout0;
output   grp_fu_1626_p_ce;
output  [31:0] grp_fu_1622_p_din0;
output  [31:0] grp_fu_1622_p_din1;
output  [0:0] grp_fu_1622_p_opcode;
input  [31:0] grp_fu_1622_p_dout0;
output   grp_fu_1622_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln41_reg_273;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [13:0] RNN_HIDDEN_WEIGHTS_TRANSPOSED_address0;
wire   [31:0] RNN_HIDDEN_WEIGHTS_TRANSPOSED_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln41_fu_127_p2;
reg   [0:0] icmp_ln41_reg_273_pp0_iter1_reg;
wire   [0:0] icmp_ln43_fu_142_p2;
reg   [0:0] icmp_ln43_reg_277;
reg   [0:0] icmp_ln43_reg_277_pp0_iter1_reg;
wire   [0:0] icmp_ln43_2_fu_171_p2;
reg   [0:0] icmp_ln43_2_reg_293;
reg   [0:0] icmp_ln43_2_reg_293_pp0_iter1_reg;
reg   [0:0] icmp_ln43_2_reg_293_pp0_iter2_reg;
reg   [31:0] h_t_minus_1_load_reg_297;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [6:0] select_ln41_4_fu_196_p3;
reg   [6:0] select_ln41_4_reg_302;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [6:0] select_ln41_4_reg_302_pp0_iter1_reg;
reg   [6:0] select_ln41_4_reg_302_pp0_iter2_reg;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] RNN_HIDDEN_WEIGHTS_TRANSPOSED_load_reg_317;
reg   [31:0] mul_i2_reg_322;
wire   [31:0] select_ln41_3_fu_219_p3;
reg   [31:0] run_sum_2_reg_332;
reg   [6:0] h_t_mult_weights_addr_reg_337;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln43_1_fu_156_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln44_1_fu_212_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln41_fu_227_p1;
reg   [31:0] run_sum_fu_42;
wire    ap_loop_init;
reg   [6:0] j_fu_46;
wire   [6:0] add_ln43_fu_165_p2;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [6:0] i_fu_50;
wire    ap_block_pp0_stage2;
reg   [13:0] indvar_flatten27_fu_54;
wire   [13:0] add_ln41_fu_133_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten27_load;
reg    h_t_minus_1_ce0_local;
reg    RNN_HIDDEN_WEIGHTS_TRANSPOSED_ce0_local;
reg    h_t_mult_weights_we0_local;
reg    h_t_mult_weights_ce0_local;
wire    ap_block_pp0_stage1;
wire   [6:0] select_ln41_fu_148_p3;
wire   [6:0] add_ln41_2_fu_190_p2;
wire   [13:0] grp_fu_236_p3;
wire   [6:0] grp_fu_236_p0;
wire   [6:0] grp_fu_236_p1;
wire   [6:0] grp_fu_236_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage0;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [13:0] grp_fu_236_p00;
wire   [13:0] grp_fu_236_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 run_sum_fu_42 = 32'd0;
#0 j_fu_46 = 7'd0;
#0 i_fu_50 = 7'd0;
#0 indvar_flatten27_fu_54 = 14'd0;
#0 ap_done_reg = 1'b0;
end

forward_forward_Pipeline_VITIS_LOOP_41_2_VITIS_LOOP_43_3_RNN_HIDDEN_WEIGHTS_TRANSPOSEAem #(
    .DataWidth( 32 ),
    .AddressRange( 10000 ),
    .AddressWidth( 14 ))
RNN_HIDDEN_WEIGHTS_TRANSPOSED_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RNN_HIDDEN_WEIGHTS_TRANSPOSED_address0),
    .ce0(RNN_HIDDEN_WEIGHTS_TRANSPOSED_ce0_local),
    .q0(RNN_HIDDEN_WEIGHTS_TRANSPOSED_q0)
);

forward_mac_muladd_7ns_7ns_7ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mac_muladd_7ns_7ns_7ns_14_4_1_U223(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_236_p0),
    .din1(grp_fu_236_p1),
    .din2(grp_fu_236_p2),
    .ce(1'b1),
    .dout(grp_fu_236_p3)
);

forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        i_fu_50 <= 7'd0;
    end else if (((icmp_ln41_reg_273 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        i_fu_50 <= select_ln41_4_fu_196_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_127_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten27_fu_54 <= add_ln41_fu_133_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten27_fu_54 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_127_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_46 <= add_ln43_fu_165_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_46 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        run_sum_fu_42 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        run_sum_fu_42 <= grp_fu_1622_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        RNN_HIDDEN_WEIGHTS_TRANSPOSED_load_reg_317 <= RNN_HIDDEN_WEIGHTS_TRANSPOSED_q0;
        icmp_ln41_reg_273 <= icmp_ln41_fu_127_p2;
        icmp_ln41_reg_273_pp0_iter1_reg <= icmp_ln41_reg_273;
        icmp_ln43_2_reg_293 <= icmp_ln43_2_fu_171_p2;
        icmp_ln43_2_reg_293_pp0_iter1_reg <= icmp_ln43_2_reg_293;
        icmp_ln43_2_reg_293_pp0_iter2_reg <= icmp_ln43_2_reg_293_pp0_iter1_reg;
        icmp_ln43_reg_277 <= icmp_ln43_fu_142_p2;
        icmp_ln43_reg_277_pp0_iter1_reg <= icmp_ln43_reg_277;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_t_minus_1_load_reg_297 <= h_t_minus_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        h_t_mult_weights_addr_reg_337 <= zext_ln41_fu_227_p1;
        mul_i2_reg_322 <= grp_fu_1626_p_dout0;
        run_sum_2_reg_332 <= grp_fu_1622_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        select_ln41_4_reg_302 <= select_ln41_4_fu_196_p3;
        select_ln41_4_reg_302_pp0_iter1_reg <= select_ln41_4_reg_302;
        select_ln41_4_reg_302_pp0_iter2_reg <= select_ln41_4_reg_302_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        RNN_HIDDEN_WEIGHTS_TRANSPOSED_ce0_local = 1'b1;
    end else begin
        RNN_HIDDEN_WEIGHTS_TRANSPOSED_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_273 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_273_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten27_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten27_load = indvar_flatten27_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h_t_minus_1_ce0_local = 1'b1;
    end else begin
        h_t_minus_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h_t_mult_weights_ce0_local = 1'b1;
    end else begin
        h_t_mult_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_2_reg_293_pp0_iter2_reg == 1'd1))) begin
        h_t_mult_weights_we0_local = 1'b1;
    end else begin
        h_t_mult_weights_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign RNN_HIDDEN_WEIGHTS_TRANSPOSED_address0 = zext_ln44_1_fu_212_p1;

assign add_ln41_2_fu_190_p2 = (i_fu_50 + 7'd1);

assign add_ln41_fu_133_p2 = (ap_sig_allocacmp_indvar_flatten27_load + 14'd1);

assign add_ln43_fu_165_p2 = (select_ln41_fu_148_p3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign grp_fu_1622_p_ce = 1'b1;

assign grp_fu_1622_p_din0 = select_ln41_3_fu_219_p3;

assign grp_fu_1622_p_din1 = mul_i2_reg_322;

assign grp_fu_1622_p_opcode = 2'd0;

assign grp_fu_1626_p_ce = 1'b1;

assign grp_fu_1626_p_din0 = h_t_minus_1_load_reg_297;

assign grp_fu_1626_p_din1 = RNN_HIDDEN_WEIGHTS_TRANSPOSED_load_reg_317;

assign grp_fu_236_p0 = grp_fu_236_p00;

assign grp_fu_236_p00 = select_ln41_fu_148_p3;

assign grp_fu_236_p1 = 14'd100;

assign grp_fu_236_p2 = grp_fu_236_p20;

assign grp_fu_236_p20 = select_ln41_4_fu_196_p3;

assign h_t_minus_1_address0 = zext_ln43_1_fu_156_p1;

assign h_t_minus_1_ce0 = h_t_minus_1_ce0_local;

assign h_t_mult_weights_address0 = h_t_mult_weights_addr_reg_337;

assign h_t_mult_weights_ce0 = h_t_mult_weights_ce0_local;

assign h_t_mult_weights_d0 = run_sum_2_reg_332;

assign h_t_mult_weights_we0 = h_t_mult_weights_we0_local;

assign icmp_ln41_fu_127_p2 = ((ap_sig_allocacmp_indvar_flatten27_load == 14'd10000) ? 1'b1 : 1'b0);

assign icmp_ln43_2_fu_171_p2 = ((add_ln43_fu_165_p2 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_142_p2 = ((ap_sig_allocacmp_j_load == 7'd100) ? 1'b1 : 1'b0);

assign select_ln41_3_fu_219_p3 = ((icmp_ln43_reg_277_pp0_iter1_reg[0:0] == 1'b1) ? 32'd0 : run_sum_fu_42);

assign select_ln41_4_fu_196_p3 = ((icmp_ln43_reg_277[0:0] == 1'b1) ? add_ln41_2_fu_190_p2 : i_fu_50);

assign select_ln41_fu_148_p3 = ((icmp_ln43_fu_142_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign zext_ln41_fu_227_p1 = select_ln41_4_reg_302_pp0_iter2_reg;

assign zext_ln43_1_fu_156_p1 = select_ln41_fu_148_p3;

assign zext_ln44_1_fu_212_p1 = grp_fu_236_p3;

endmodule //forward_forward_Pipeline_VITIS_LOOP_41_2_VITIS_LOOP_43_3
