-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity forward_forward_Pipeline_VITIS_LOOP_134_4_MEANS_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 24
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of forward_forward_Pipeline_VITIS_LOOP_134_4_MEANS_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110111011001101101111111101", 1 => "00111110111011001101101111111101", 2 => "10111111001100100001010001010111", 3 => "00111111110101001110000101000100", 
    4 => "10111110000010000001000011110011", 5 => "10111110000010000001000011110010", 6 => "10111111100000100101010000100110", 7 => "00111111001000011010010101101101", 
    8 => "10111101101110110010101111100110", 9 => "10111101101110110010101111100111", 10 => "10111111011101101000000010001001", 11 => "00111111010111011101100000001001", 
    12 => "11000000110001011110010000000011", 13 => "11000000110001011110010000000011", 14 => "11000011010000000111011100110100", 15 => "01000011001010111101000001111001", 
    16 => "10111111101101000011101010100110", 17 => "10111111101101000011101010100111", 18 => "11000011010101000101000101010001", 19 => "01000011010000011000010010000011", 
    20 => "00111111001110110111010100011100", 21 => "00111111001110110111010100011101", 22 => "11000011001001000000010000110111", 23 => "01000011010000010111110000011000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

