-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity forward_forward_Pipeline_VITIS_LOOP_134_4_STD_DEVS_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 24
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of forward_forward_Pipeline_VITIS_LOOP_134_4_STD_DEVS_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111111100001111101110000000000", 1 => "00111110110011111111110111100011", 2 => "00111111101010110011100010010100", 3 => "00111111100111000101011100011111", 
    4 => "00111111010110000101101010110111", 5 => "00111111000101011111101000010110", 6 => "00111111100111100101001001110111", 7 => "00111111010100111111110100010111", 
    8 => "00111111100011101010010001101010", 9 => "00111111010111111100011110100111", 10 => "00111111110000111101101001010011", 11 => "00111111010100011110111101110000", 
    12 => "01000011000101111010000001011000", 13 => "01000001110011101000111010110101", 14 => "01000011001111100111101000011110", 15 => "01000011001001010100010110111011", 
    16 => "01000011011100110111011110110001", 17 => "01000001111011010110010100101010", 18 => "01000011100010101001101010111010", 19 => "01000011100000110111101101011111", 
    20 => "01000011000111110101100001010010", 21 => "01000001111101111100111111100100", 22 => "01000011000101001001000000100001", 23 => "01000011010000101100111110110101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

