# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_forward_0_25/design_1_forward_0_25.xci
# IP: The module: 'design_1_forward_0_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_dadd_64ns_64ns_64_5_full_dsp_1_ip/forward_dadd_64ns_64ns_64_5_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_dadd_64ns_64ns_64_5_full_dsp_1_ip || ORIG_REF_NAME==forward_dadd_64ns_64ns_64_5_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip || ORIG_REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip/forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip || ORIG_REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip || ORIG_REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip || ORIG_REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_ip || ORIG_REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip || ORIG_REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fpext_32ns_64_2_no_dsp_1_ip/forward_fpext_32ns_64_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==forward_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fptrunc_64ns_32_2_no_dsp_1_ip/forward_fptrunc_64ns_32_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fptrunc_64ns_32_2_no_dsp_1_ip || ORIG_REF_NAME==forward_fptrunc_64ns_32_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fsub_32ns_32ns_32_4_full_dsp_1_ip/forward_fsub_32ns_32ns_32_4_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fsub_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==forward_fsub_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/constraints/forward_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_forward_0_25'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_forward_0_25/design_1_forward_0_25.xci
# IP: The module: 'design_1_forward_0_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_dadd_64ns_64ns_64_5_full_dsp_1_ip/forward_dadd_64ns_64ns_64_5_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_dadd_64ns_64ns_64_5_full_dsp_1_ip || ORIG_REF_NAME==forward_dadd_64ns_64ns_64_5_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip/forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip || ORIG_REF_NAME==forward_fadd_32ns_32ns_32_4_full_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip/forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==forward_faddfsub_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip/forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip || ORIG_REF_NAME==forward_fcmp_32ns_32ns_1_2_no_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip || ORIG_REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip/forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip || ORIG_REF_NAME==forward_fdiv_32ns_32ns_32_9_no_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_ip || ORIG_REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip/forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip || ORIG_REF_NAME==forward_fmul_32ns_32ns_32_3_max_dsp_1_x_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fpext_32ns_64_2_no_dsp_1_ip/forward_fpext_32ns_64_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==forward_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fptrunc_64ns_32_2_no_dsp_1_ip/forward_fptrunc_64ns_32_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fptrunc_64ns_32_2_no_dsp_1_ip || ORIG_REF_NAME==forward_fptrunc_64ns_32_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/hdl/ip/forward_fsub_32ns_32ns_32_4_full_dsp_1_ip/forward_fsub_32ns_32ns_32_4_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==forward_fsub_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==forward_fsub_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_forward_0_25/constraints/forward_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_forward_0_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
