# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_27/design_1_rst_ps8_0_96M_27.xci
# IP: The module: 'design_1_rst_ps8_0_96M_27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_27/design_1_rst_ps8_0_96M_27_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_27'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_27/design_1_rst_ps8_0_96M_27_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_27'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_27/design_1_rst_ps8_0_96M_27.xci
# IP: The module: 'design_1_rst_ps8_0_96M_27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_27/design_1_rst_ps8_0_96M_27_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_27'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_27/design_1_rst_ps8_0_96M_27_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_96M_27'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
