# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/design_1_axi_smc_1_22.xci
# IP: The module: 'design_1_axi_smc_1_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/bd_9728.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_0/bd_9728_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_1/bd_9728_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_2/bd_9728_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_3/bd_9728_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_4/bd_9728_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_5/bd_9728_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_6/bd_9728_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_7/bd_9728_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_8/bd_9728_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_9/bd_9728_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_10/bd_9728_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_11/bd_9728_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_12/bd_9728_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_13/bd_9728_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_14/bd_9728_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_15/bd_9728_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_16/bd_9728_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_17/bd_9728_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_18/bd_9728_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_19/bd_9728_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_20/bd_9728_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_21/bd_9728_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_22/bd_9728_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_23/bd_9728_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_24/bd_9728_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_25/bd_9728_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_26/bd_9728_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_1/bd_9728_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_2/bd_9728_arsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_3/bd_9728_rsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_4/bd_9728_awsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_5/bd_9728_wsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_6/bd_9728_bsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_10/bd_9728_s00a2s_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_11/bd_9728_sarn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_12/bd_9728_srn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_16/bd_9728_s01a2s_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_17/bd_9728_sawn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_18/bd_9728_swn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_19/bd_9728_sbn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_20/bd_9728_m00s2a_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_21/bd_9728_m00arn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_22/bd_9728_m00rn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_23/bd_9728_m00awn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_24/bd_9728_m00wn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_25/bd_9728_m00bn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_22'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/design_1_axi_smc_1_22.xci
# IP: The module: 'design_1_axi_smc_1_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/bd_9728.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_0/bd_9728_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_1/bd_9728_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_2/bd_9728_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_3/bd_9728_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_4/bd_9728_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_5/bd_9728_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_6/bd_9728_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_7/bd_9728_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_8/bd_9728_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_9/bd_9728_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_10/bd_9728_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_11/bd_9728_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_12/bd_9728_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_13/bd_9728_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_14/bd_9728_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_15/bd_9728_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_16/bd_9728_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_17/bd_9728_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_18/bd_9728_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_19/bd_9728_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_20/bd_9728_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_21/bd_9728_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_22/bd_9728_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_23/bd_9728_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_24/bd_9728_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_25/bd_9728_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_26/bd_9728_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_1/bd_9728_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_2/bd_9728_arsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_3/bd_9728_rsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_4/bd_9728_awsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_5/bd_9728_wsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_6/bd_9728_bsw_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_10/bd_9728_s00a2s_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_11/bd_9728_sarn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_12/bd_9728_srn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_16/bd_9728_s01a2s_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_17/bd_9728_sawn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_18/bd_9728_swn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_19/bd_9728_sbn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_20/bd_9728_m00s2a_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_21/bd_9728_m00arn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_22/bd_9728_m00rn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_23/bd_9728_m00awn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_24/bd_9728_m00wn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/bd_0/ip/ip_25/bd_9728_m00bn_0_ooc.xdc

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tjjtj/Desktop/NUS/Y4S1/CG4002/Hardware_NN/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_22/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
